package model

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/redis/go-redis/v9"
	bip39 "github.com/tyler-smith/go-bip39"
	"github.com/urnetwork/server"
	"github.com/urnetwork/server/jwt"
)

var ErrProberShardRetired = errors.New("probe shard execution is retired")

// These IDs are generated by the task owner, never accepted from an API payer.
// Each execution gets a different network, including a retry of the same task.
type ProberShardKey struct {
	TaskId     server.Id
	Epoch      server.Id
	ShardIndex int
	ShardCount int
}

type ProberShardOwner struct {
	Key              ProberShardKey
	NetworkId        server.Id
	UserId           server.Id
	ClientId         server.Id
	DeviceId         server.Id
	BalanceId        server.Id
	State            string
	Deadline         time.Time
	RetiredClientIds []server.Id
}

const proberShardColumns = `task_id, epoch, shard_index, shard_count, network_id, user_id, client_id, device_id, balance_id, state, deadline, retired_client_ids`

func scanProberShard(row interface{ Scan(...any) error }) (*ProberShardOwner, error) {
	owner := &ProberShardOwner{}
	err := row.Scan(&owner.Key.TaskId, &owner.Key.Epoch, &owner.Key.ShardIndex, &owner.Key.ShardCount,
		&owner.NetworkId, &owner.UserId, &owner.ClientId, &owner.DeviceId, &owner.BalanceId, &owner.State, &owner.Deadline, &owner.RetiredClientIds)
	return owner, err
}

// BeginProberShard commits creation and its ownership record together. A lost
// reply can replay this epoch; a process crash cannot leave an untracked account.
// There is exactly one funded row in this private network and no global top-up.
func BeginProberShard(ctx context.Context, key ProberShardKey, credit ByteCount, lifetime time.Duration) (owner *ProberShardOwner, returnErr error) {
	if key.TaskId == (server.Id{}) || key.Epoch == (server.Id{}) || key.ShardIndex < 0 || key.ShardCount <= key.ShardIndex || key.ShardCount > 256 || credit <= 0 || lifetime <= 0 || lifetime > 24*time.Hour {
		return nil, errors.New("invalid probe shard ownership or funding")
	}
	return server.HandleError2(func() (*ProberShardOwner, error) {
		server.Tx(ctx, func(tx server.PgTx) {
			owner, returnErr = nil, nil
			// Stable shard admission orders geometry changes and task retries.
			server.RaisePgResult(tx.Exec(ctx, `SELECT pg_advisory_xact_lock(192847301, $1)`, key.ShardIndex))
			var now time.Time
			server.Raise(tx.QueryRow(ctx, `SELECT clock_timestamp() AT TIME ZONE 'UTC'`).Scan(&now))
			rows, err := tx.Query(ctx, `SELECT `+proberShardColumns+` FROM prober_shard_run WHERE task_id=$1 AND epoch=$2 FOR UPDATE`, key.TaskId, key.Epoch)
			server.WithPgResult(rows, err, func() {
				if rows.Next() {
					owner, err = scanProberShard(rows)
					server.Raise(err)
				}
			})
			if owner != nil {
				if owner.Key != key || owner.State != "active" || !now.Before(owner.Deadline) {
					returnErr = ErrProberShardRetired
				}
				return
			}
			// A new epoch must retire a previous owner before minting anything.
			var previous *ProberShardOwner
			rows, err = tx.Query(ctx, `SELECT `+proberShardColumns+` FROM prober_shard_run WHERE shard_index=$1 AND state='active' FOR UPDATE`, key.ShardIndex)
			server.WithPgResult(rows, err, func() {
				if rows.Next() {
					previous, err = scanProberShard(rows)
					server.Raise(err)
				}
			})
			if previous != nil {
				server.Raise(drainProberShardInTx(ctx, tx, previous))
			}
			// The replacement grant id is fresh and unpublished until commit;
			// only the previous owner's existing grant needs shared ownership.
			owner = &ProberShardOwner{Key: key, NetworkId: server.NewId(), UserId: server.NewId(), ClientId: server.NewId(), DeviceId: server.NewId(), BalanceId: server.NewId(), State: "active", Deadline: now.Add(lifetime)}
			name := "probe-" + owner.NetworkId.String()
			// Machine accounts use the normal seedphrase hash, not a retained root
			// secret. No public signup/rate-limit or second transaction is involved.
			entropy, err := bip39.NewEntropy(256)
			server.Raise(err)
			phrase, err := bip39.NewMnemonic(entropy)
			server.Raise(err)
			server.RaisePgResult(tx.Exec(ctx, `INSERT INTO network_user(user_id,user_name,auth_type) VALUES($1,$2,$3)`, owner.UserId, name, AuthTypeSeedphrase))
			server.Raise(CreateSeedphraseAuthInTx(tx, ctx, owner.UserId, phrase))
			server.RaisePgResult(tx.Exec(ctx, `INSERT INTO network(network_id,network_name,admin_user_id) VALUES($1,$2,$3)`, owner.NetworkId, name, owner.UserId))
			server.RaisePgResult(tx.Exec(ctx, `INSERT INTO device(device_id,network_id,device_name,device_spec) VALUES($1,$2,$3,$4)`, owner.DeviceId, owner.NetworkId, ProberClientDescription, ProberClientDeviceSpec))
			server.RaisePgResult(tx.Exec(ctx, `INSERT INTO network_client(client_id,network_id,device_id,description,create_time,auth_time) VALUES($1,$2,$3,$4,$5,$5)`, owner.ClientId, owner.NetworkId, owner.DeviceId, ProberClientDescription, now))
			server.RaisePgResult(tx.Exec(ctx, `INSERT INTO transfer_balance(balance_id,network_id,start_time,end_time,start_balance_byte_count,balance_byte_count,net_revenue_nano_cents,subsidy_net_revenue_nano_cents,pro) VALUES($1,$2,$3,$4,$5,$5,0,0,false)`, owner.BalanceId, owner.NetworkId, now, owner.Deadline.Add(24*time.Hour), credit))
			server.RaisePgResult(tx.Exec(ctx, `INSERT INTO prober_shard_run(task_id,epoch,shard_index,shard_count,network_id,user_id,client_id,device_id,balance_id,state,create_time,deadline,next_cleanup_time) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'active',$10,$11,$11)`, key.TaskId, key.Epoch, key.ShardIndex, key.ShardCount, owner.NetworkId, owner.UserId, owner.ClientId, owner.DeviceId, owner.BalanceId, now, owner.Deadline))
		}, server.TxReadCommitted, server.OptNoRetry())
		if returnErr != nil {
			return nil, returnErr
		}
		return owner, nil
	}, func(err error) (*ProberShardOwner, error) { return nil, err })
}

// ProberShardIdentity returns a runtime credential only for this active epoch.
// It never creates a replacement client or stores a JWT in task arguments.
func ProberShardIdentity(ctx context.Context, owner *ProberShardOwner) (*ProberIdentity, error) {
	if owner == nil {
		return nil, ErrProberShardRetired
	}
	return server.HandleError2(func() (*ProberIdentity, error) {
		var name string
		server.Db(ctx, func(conn server.PgConn) {
			server.Raise(conn.QueryRow(ctx, `SELECT n.network_name FROM prober_shard_run r JOIN network n USING(network_id) JOIN network_client c ON c.client_id=r.client_id AND c.network_id=r.network_id WHERE r.task_id=$1 AND r.epoch=$2 AND r.state='active' AND clock_timestamp() AT TIME ZONE 'UTC'<r.deadline AND c.active`, owner.Key.TaskId, owner.Key.Epoch).Scan(&name))
		})
		token := jwt.NewByJwt(owner.NetworkId, owner.UserId, name, false, false).Client(owner.DeviceId, owner.ClientId).Sign()
		return &ProberIdentity{NetworkId: &owner.NetworkId, UserId: &owner.UserId, ClientId: &owner.ClientId, NetworkName: name, ByClientJwt: token}, nil
	}, func(err error) (*ProberIdentity, error) {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrProberShardRetired
		}
		return nil, err
	})
}

// Client creation holds a shared ownership lock until its INSERT commits.
// Draining takes the exclusive lock before enumerating/deactivating clients,
// so a late derived-client callback cannot escape the teardown cohort.
func lockProberShardClientAdmissionInTx(ctx context.Context, tx server.PgTx, networkId server.Id) error {
	_, err := lockProberShardClientAdmissionDeadlineInTx(ctx, tx, networkId)
	return err
}

// Keep the registry lock first, but carry its immutable deadline across later
// endpoint waits. Projecting a clock inside a locking SELECT can precede the
// lock wait, so even this first check reads the clock after acquiring the row.
func lockProberShardClientAdmissionDeadlineInTx(ctx context.Context, tx server.PgTx, networkId server.Id) (*time.Time, error) {
	var state string
	var deadline time.Time
	var admissionDeadline *time.Time
	rows, err := tx.Query(ctx, `SELECT state, deadline FROM prober_shard_run WHERE network_id=$1 FOR SHARE`, networkId)
	// Only the retired-shard policy refusal returns normally. Operational
	// failures must unwind the enclosing void Tx callback: otherwise it reaches
	// COMMIT after a failed admission read and can mask cancellation with a
	// statement-cache/closed-connection error, or commit earlier caller writes.
	server.Raise(err)
	defer rows.Close()
	if rows.Next() {
		server.Raise(rows.Scan(&state, &deadline))
		if state != "active" {
			return nil, ErrProberShardRetired
		}
		admissionDeadline = &deadline
	}
	rows.Close()
	server.Raise(rows.Err())
	return admissionDeadline, validateProberShardAdmissionDeadlineInTx(ctx, tx, admissionDeadline)
}

// A private probe account may fund only contracts in which it is an endpoint;
// two different shard accounts never share a contract or payer. Lock ownership
// before grants or clients: drain locks the registry, clients, then its grant.
// The shared registry fence prevents an admission waiting on a grant from
// deadlocking with drain after it moves on to its endpoint lifecycle locks.
func validateProberShardPayerInTx(ctx context.Context, tx server.PgTx, source, destination, payer server.Id) (*time.Time, error) {
	defer server.EnterContractCreationStage(ctx, server.ContractStageShardFence)()
	rows, err := tx.Query(ctx, `SELECT network_id, state, deadline FROM prober_shard_run
		WHERE network_id=ANY($1) ORDER BY network_id FOR SHARE`, []server.Id{source, destination, payer})
	// Only policy refusals return normally. Database failures must unwind Tx;
	// otherwise its void callback appears successful and a later COMMIT masks
	// the original query/cancellation error with a closed-connection failure.
	server.Raise(err)
	defer rows.Close()
	var admissionDeadline *time.Time
	for rows.Next() {
		var network server.Id
		var state string
		var deadline time.Time
		server.Raise(rows.Scan(&network, &state, &deadline))
		if state != "active" || payer != network || (source != network && destination != network) {
			rows.Close()
			return nil, errors.New("contract is outside its probe shard payer")
		}
		if admissionDeadline == nil || deadline.Before(*admissionDeadline) {
			admissionDeadline = &deadline
		}
	}
	rows.Close()
	server.Raise(rows.Err())
	// A timestamp projected inside the locking SELECT can precede a row-lock
	// wait. Read the database clock only after every selected lock is acquired.
	return admissionDeadline, validateProberShardAdmissionDeadlineInTx(ctx, tx, admissionDeadline)
}

// Registry locks fence state changes, not the passage of time. Admission must
// recheck after any grant/census/client wait and before its financial writes.
func validateProberShardAdmissionDeadlineInTx(ctx context.Context, tx server.PgTx, deadline *time.Time) error {
	if deadline == nil {
		return nil
	}
	var live bool
	server.Raise(tx.QueryRow(ctx, `SELECT clock_timestamp() AT TIME ZONE 'UTC' < $1::timestamp`, *deadline).Scan(&live))
	if !live {
		return ErrProberShardRetired
	}
	return nil
}

// Caller owns the registry row FOR UPDATE. The existing sorted client locks
// serialize with CreateContract's FOR SHARE admission boundary.
func drainProberShardInTx(ctx context.Context, tx server.PgTx, owner *ProberShardOwner) error {
	if owner.State != "active" {
		return nil
	}
	admitted, err := tryTransferBalanceOwnershipInTx(ctx, tx, []server.Id{owner.BalanceId})
	if err != nil {
		return err
	}
	if !admitted {
		return errTransferBalanceOwnershipBusy
	}
	var clients []server.Id
	// The registry fence prevents new shard admissions. Already retired clients
	// need no second timestamp or index rewrite; lock the remaining live set in
	// the same order as ordinary deactivation before reading its common clock.
	rows, err := tx.Query(ctx, `SELECT client_id FROM network_client
		WHERE network_id=$1 AND active=true ORDER BY client_id FOR UPDATE`, owner.NetworkId)
	if err != nil {
		return err
	}
	for rows.Next() {
		var id server.Id
		if err = rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		clients = append(clients, id)
	}
	err = rows.Err()
	rows.Close()
	if err != nil {
		return err
	}
	if _, err = deactivateLockedNetworkClientsInTx(ctx, tx, clients, owner.NetworkId); err != nil {
		return err
	}
	// active is a generated amount predicate. Expire admission without changing
	// consumed credit or the settlement principal still needed by open escrow.
	if _, err = tx.Exec(ctx, `UPDATE transfer_balance SET end_time=LEAST(end_time,clock_timestamp() AT TIME ZONE 'UTC') WHERE balance_id=$1 AND network_id=$2`, owner.BalanceId, owner.NetworkId); err != nil {
		return err
	}
	_, err = tx.Exec(ctx, `UPDATE prober_shard_run SET state='draining',next_cleanup_time=clock_timestamp() AT TIME ZONE 'UTC' WHERE task_id=$1 AND epoch=$2 AND state<>'closed'`, owner.Key.TaskId, owner.Key.Epoch)
	return err
}

func DrainProberShard(ctx context.Context, key ProberShardKey) error {
	_, err := server.HandleError2(func() (struct{}, error) {
		server.Tx(ctx, func(tx server.PgTx) {
			owner, err := scanProberShard(tx.QueryRow(ctx, `SELECT `+proberShardColumns+` FROM prober_shard_run WHERE task_id=$1 AND epoch=$2 FOR UPDATE`, key.TaskId, key.Epoch))
			server.Raise(err)
			if owner.Key != key {
				server.Raise(fmt.Errorf("probe shard owner mismatch"))
			}
			server.Raise(drainProberShardInTx(ctx, tx, owner))
		}, server.TxReadCommitted, server.OptNoRetry())
		return struct{}{}, nil
	}, func(err error) (struct{}, error) { return struct{}{}, err })
	return err
}

// The full payer index was removed; the newer unresolved-payer partial index
// excludes disputed contracts. A bare payer/outcome predicate can therefore
// scan the global outcome index even for an empty private shard. Constrain both
// leading keys of the retained (open,payer_network_id,transfer_byte_count) index.
// Keep outcome outside OFFSET 0, so a false-zero global partial index cannot
// replace these two payer ranges. Both generated-open values are necessary:
// disputed unresolved and unanchored zero-byte contracts still block deletion.
// Work is scoped to this short-lived payer's history, not the global live set.
const proberShardPayerContractScopeSql = `
	CROSS JOIN (VALUES (true), (false)) AS contract_state(open)
	CROSS JOIN LATERAL (
		SELECT contract_id, outcome
		FROM transfer_contract
		WHERE open=contract_state.open AND payer_network_id=payer_scope.network_id
		OFFSET 0
	) AS scoped_contract
`

const proberShardReportedContractsSql = `
	SELECT scoped_contract.contract_id
	FROM (
		SELECT network_id FROM prober_shard_run
		WHERE task_id=$1 AND epoch=$2 AND state='draining'
	) AS payer_scope
` + proberShardPayerContractScopeSql + `
	CROSS JOIN LATERAL (
		SELECT 1 FROM contract_close
		WHERE contract_id=scoped_contract.contract_id AND party=$3 AND NOT checkpoint
		LIMIT 1 OFFSET 0
	) AS source_final
	CROSS JOIN LATERAL (
		SELECT 1 FROM contract_close
		WHERE contract_id=scoped_contract.contract_id AND party=$4 AND NOT checkpoint
		LIMIT 1 OFFSET 0
	) AS destination_final
	WHERE scoped_contract.outcome IS NULL
	ORDER BY scoped_contract.contract_id LIMIT 32
`

const proberShardHasUnresolvedContractsSql = `
	SELECT EXISTS (
		SELECT 1 FROM (SELECT $1::uuid AS network_id) AS payer_scope
` + proberShardPayerContractScopeSql + `
		WHERE scoped_contract.outcome IS NULL
	)
`

// Retry only contracts whose two actual final reports already authorize normal
// settlement. This runs without an ownership/balance lock: settlement keeps its
// existing contract-before-balance lock order. Missing/checkpoint reports and
// terminal-but-unsettled accounting remain debt, never invented zero usage.
func settleReportedProberShardContracts(ctx context.Context, key ProberShardKey) error {
	var contracts []server.Id
	server.Db(ctx, func(conn server.PgConn) {
		rows, err := conn.Query(ctx, proberShardReportedContractsSql,
			key.TaskId, key.Epoch, ContractPartySource, ContractPartyDestination)
		server.WithPgResult(rows, err, func() {
			for rows.Next() {
				var id server.Id
				server.Raise(rows.Scan(&id))
				contracts = append(contracts, id)
			}
		})
	})
	for _, id := range contracts {
		closed, err := settleContract(ctx, id)
		if err != nil {
			return err
		}
		if closed {
			RemoveFromStream(ctx, id)
		}
	}
	return nil
}

// ReapProberShard never guesses usage or erases an unsettled financial row. A
// blocked owner stays durably draining and is retried by the recurring task.
func ReapProberShard(ctx context.Context, key ProberShardKey) (deleted bool, returnErr error) {
	return server.HandleError2(func() (bool, error) {
		// Persist retry progress before settlement or Redis work can fail. A
		// broken owner must not monopolize the next bounded cleanup page.
		server.Tx(ctx, func(tx server.PgTx) {
			server.RaisePgResult(tx.Exec(ctx, `UPDATE prober_shard_run
				SET next_cleanup_time=(clock_timestamp() AT TIME ZONE 'UTC')+interval '1 minute'
				WHERE task_id=$1 AND epoch=$2 AND state IN ('draining','deleted')`, key.TaskId, key.Epoch))
		}, server.TxReadCommitted, server.OptNoRetry())
		if err := settleReportedProberShardContracts(ctx, key); err != nil {
			return false, err
		}
		var cacheOwner *ProberShardOwner
		server.Tx(ctx, func(tx server.PgTx) {
			deleted = false
			cacheOwner = nil
			owner, err := scanProberShard(tx.QueryRow(ctx, `SELECT `+proberShardColumns+` FROM prober_shard_run WHERE task_id=$1 AND epoch=$2 FOR UPDATE`, key.TaskId, key.Epoch))
			server.Raise(err)
			if owner.Key != key {
				server.Raise(errors.New("probe shard owner mismatch"))
			}
			if owner.State == "closed" {
				deleted = true
				return
			}
			if owner.State == "deleted" {
				cacheOwner = owner
				return
			}
			if owner.State != "draining" {
				return
			}
			admitted, ownershipErr := tryTransferBalanceOwnershipInTx(ctx, tx, []server.Id{owner.BalanceId})
			server.Raise(ownershipErr)
			if !admitted {
				server.Raise(errTransferBalanceOwnershipBusy)
			}
			// Registry precedes the compatibility bridge; grants and client
			// teardown follow it, matching normal authenticated admission.
			server.RaisePgResult(tx.Exec(ctx, `SELECT pg_advisory_xact_lock_shared(-776::bigint)`))
			// Settlement takes a contract lock before the balance lock. This read
			// never locks contracts while holding a balance: its post-lock snapshot
			// either sees a completed debit or retains the open/unsettled debt.
			var found, plain bool
			rows, err := tx.Query(ctx, `SELECT NOT paid AND NOT pro AND net_revenue_nano_cents=0 AND subsidy_net_revenue_nano_cents=0 FROM transfer_balance WHERE balance_id=$1 AND network_id=$2 FOR UPDATE`, owner.BalanceId, owner.NetworkId)
			server.WithPgResult(rows, err, func() {
				if rows.Next() {
					server.Raise(rows.Scan(&plain))
					found = true
				}
			})
			if !found || !plain {
				server.Raise(errors.New("probe shard funding record is missing or changed"))
			}
			var blocked bool
			server.Raise(tx.QueryRow(ctx, `SELECT
				EXISTS (SELECT 1 FROM transfer_escrow WHERE balance_id=$1 AND NOT settled) OR
				EXISTS (SELECT 1 FROM transfer_debit_journal WHERE balance_id=$1) OR
				EXISTS (SELECT 1 FROM transfer_balance WHERE network_id=$2 AND balance_id<>$1)`, owner.BalanceId, owner.NetworkId).Scan(&blocked))
			if blocked {
				return
			}
			server.Raise(tx.QueryRow(ctx, proberShardHasUnresolvedContractsSql, owner.NetworkId).Scan(&blocked))
			if blocked {
				return
			}
			// Probe tunnels create ordinary clients, not hosted proxy devices.
			// Preserve any unexpected hosted resource for explicit cleanup rather
			// than deleting its credential owner underneath an active proxy.
			server.Raise(tx.QueryRow(ctx, `SELECT EXISTS (
				SELECT 1 FROM network_client c JOIN proxy_device_config p USING(client_id)
				WHERE c.network_id=$1
			) OR EXISTS (
				SELECT 1 FROM network_client c JOIN proxy_client p USING(client_id)
				WHERE c.network_id=$1
			)`, owner.NetworkId).Scan(&blocked))
			if blocked {
				return
			}
			// validateProberShardPayerInTx requires this payer for every private
			// contract (including zero-byte/companions) and rejects no-payer
			// creation. The indexed payer test above therefore covers the whole
			// owner without one history scan per transient child client.
			// The owning tunnel must disconnect before its identity is removed.
			server.Raise(tx.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM network_client c JOIN network_client_connection x USING(client_id) WHERE c.network_id=$1 AND x.connected)`, owner.NetworkId).Scan(&blocked))
			if blocked {
				return
			}
			clients := []server.Id{owner.ClientId}
			rows, err = tx.Query(ctx, `SELECT client_id FROM network_client WHERE network_id=$1 ORDER BY client_id`, owner.NetworkId)
			server.WithPgResult(rows, err, func() {
				for rows.Next() {
					var id server.Id
					server.Raise(rows.Scan(&id))
					clients = append(clients, id)
				}
			})
			slices.SortFunc(clients, func(a, b server.Id) int { return a.Cmp(b) })
			clients = slices.Compact(clients)
			providerWorkLockCurrentSessionMutationInTx(ctx, tx, clients...)
			server.Raise(tx.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM network_client_connection WHERE client_id=ANY($1) AND connected)`, clients).Scan(&blocked))
			if blocked {
				return
			}
			// The durable post-delete record retains this cohort if Redis is down
			// or the worker exits after the SQL commit. No identity can be reminted
			// once the owner leaves active, and client UUIDs are never reused.
			owner.RetiredClientIds = clients
			// These accounts only own their one device and authentication record.
			// Financial contracts, sweeps, signed history and balance revision
			// tombstones deliberately outlive the disposable account.
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM client_tls_certificate WHERE client_id=ANY($1)`, clients))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM network_client_role WHERE client_id=ANY($1)`, clients))
			server.RaisePgResult(tx.Exec(ctx, `WITH connections AS MATERIALIZED (
				SELECT connection_id FROM network_client_connection WHERE client_id=ANY($1)
			), locations AS (DELETE FROM network_client_location WHERE connection_id IN (SELECT connection_id FROM connections)),
			latencies AS (DELETE FROM network_client_latency WHERE connection_id IN (SELECT connection_id FROM connections)),
			speeds AS (DELETE FROM network_client_speed WHERE connection_id IN (SELECT connection_id FROM connections))
			DELETE FROM network_client_connection WHERE client_id=ANY($1)`, clients))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM provide_key WHERE client_id=ANY($1)`, clients))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM network_client WHERE network_id=$1`, owner.NetworkId))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM device WHERE network_id=$1`, owner.NetworkId))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM transfer_balance WHERE balance_id=$1 AND network_id=$2`, owner.BalanceId, owner.NetworkId))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM network WHERE network_id=$1 AND admin_user_id=$2`, owner.NetworkId, owner.UserId))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM network_user_auth_seedphrase WHERE user_id=$1`, owner.UserId))
			server.RaisePgResult(tx.Exec(ctx, `DELETE FROM network_user WHERE user_id=$1`, owner.UserId))
			server.RaisePgResult(tx.Exec(ctx, `UPDATE prober_shard_run SET state='deleted',retired_client_ids=$3,close_time=clock_timestamp() AT TIME ZONE 'UTC' WHERE task_id=$1 AND epoch=$2`, key.TaskId, key.Epoch, clients))
			cacheOwner = owner
		}, server.TxReadCommitted, server.OptNoRetry())
		if cacheOwner != nil {
			// Ordinary model cleanup uses bounded cross-slot pipelines. Keep all
			// Redis I/O outside the transaction and repeat safely after a crash.
			removeReapedClientRedisState(ctx, cacheOwner.RetiredClientIds)
			forEachReapedClientRedisChunk(cacheOwner.RetiredClientIds, func(ids []server.Id) {
				server.Redis(ctx, func(r server.RedisClient) {
					_, err := r.Pipelined(ctx, func(pipe redis.Pipeliner) error {
						for _, id := range ids {
							pipe.Del(ctx, residentKey(id))
							pipe.Del(ctx, provideModesKey(id))
							for mode := ProvideModeDefault; mode <= ProvideModeStream; mode++ {
								pipe.Del(ctx, provideModeSecretKeyKey(id, mode))
							}
						}
						return nil
					})
					server.Raise(err)
				})
			})
			refreshNetEscrow(ctx, []server.Id{cacheOwner.BalanceId})
			server.Tx(ctx, func(tx server.PgTx) {
				server.RaisePgResult(tx.Exec(ctx, `UPDATE prober_shard_run SET state='closed',retired_client_ids='{}' WHERE task_id=$1 AND epoch=$2 AND state='deleted'`, key.TaskId, key.Epoch))
			}, server.TxReadCommitted, server.OptNoRetry())
			deleted = true
		}
		return deleted, nil
	}, func(err error) (bool, error) { return false, err })
}

// One bounded pass; the durable timestamp advances even when settlement still
// blocks deletion. Expired or crashed active epochs are fenced before reaping.
func ReapDueProberShards(ctx context.Context, limit int) (int, error) {
	if limit < 1 || limit > 256 {
		return 0, errors.New("invalid probe shard cleanup limit")
	}
	return server.HandleError2(func() (int, error) {
		var owners []*ProberShardOwner
		server.Tx(ctx, func(tx server.PgTx) {
			owners = nil
			rows, err := tx.Query(ctx, `SELECT `+proberShardColumns+` FROM prober_shard_run WHERE state<>'closed' AND next_cleanup_time<=clock_timestamp() AT TIME ZONE 'UTC' ORDER BY next_cleanup_time,task_id,epoch LIMIT $1 FOR UPDATE SKIP LOCKED`, limit)
			server.WithPgResult(rows, err, func() {
				for rows.Next() {
					owner, err := scanProberShard(rows)
					server.Raise(err)
					owners = append(owners, owner)
				}
			})
			server.BatchInTx(ctx, tx, func(batch server.PgBatch) {
				for _, owner := range owners {
					batch.Queue(`UPDATE prober_shard_run SET next_cleanup_time=(clock_timestamp() AT TIME ZONE 'UTC')+interval '1 minute' WHERE task_id=$1 AND epoch=$2`, owner.Key.TaskId, owner.Key.Epoch)
				}
			})
		}, server.TxReadCommitted, server.OptNoRetry())
		removed := 0
		var cleanupErr error
		for _, owner := range owners {
			if err := ctx.Err(); err != nil {
				return removed, err
			}
			if err := DrainProberShard(ctx, owner.Key); err != nil {
				cleanupErr = errors.Join(cleanupErr, err)
				continue
			}
			deleted, err := ReapProberShard(ctx, owner.Key)
			if err != nil {
				cleanupErr = errors.Join(cleanupErr, err)
				continue
			}
			if deleted {
				removed++
			}
		}
		return removed, cleanupErr
	}, func(err error) (int, error) { return 0, err })
}
