package server

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/urnetwork/connect"
)

// These tests exercise the TestEnv retry loop with hermetic lifecycle
// boundaries: a flaky failure on early attempts is retried and rescued, while
// a failure that persists across every attempt still fails the test.

func retryTestEnv(rerunCount int) *TestEnv {
	return &TestEnv{
		ApplyDbMigrations: false,
		RerunCount:        rerunCount,
		RerunTimeout:      0,
	}
}

// Avoids provisioning PostgreSQL and Redis for tests concerned only with the
// retry state machine.
func runRetryTestEnv(t *testing.T, testEnv *TestEnv, callback func(testing.TB)) {
	testEnv.runWithSetup(
		t,
		callback,
		func() error {
			return nil
		},
		func() func() {
			return func() {}
		},
	)
}

// Pins the lifecycle ordering that os.Exit would otherwise cut short.
func TestRunTestMainTearsDownBeforeReturningStatus(t *testing.T) {
	events := []string{}
	status := runTestMain(
		func() func() {
			events = append(events, "setup")
			return func() {
				events = append(events, "teardown")
			}
		},
		func() int {
			events = append(events, "run")
			return 23
		},
	)
	connect.AssertEqual(t, status, 23)
	connect.AssertEqual(t, events, []string{"setup", "run", "teardown"})
}

// Accepts only identifiers generated by TestEnv setup, so cleanup SQL never
// interpolates a catalog name that merely shares the test_ prefix.
func TestParseTestPgDbNameValidatesFullIdentifier(t *testing.T) {
	millis, ok := parseTestPgDbName("test_123_00112233445566778899aabbccddeeff")
	connect.AssertEqual(t, millis, int64(123))
	connect.AssertEqual(t, ok, true)

	invalidNames := []string{
		"test_123_0011",
		"test_not-a-time_00112233445566778899aabbccddeeff",
		"test_123_00112233445566778899aabbccddeeff_extra",
		"test_123_00112233445566778899aabbccddeezz",
		"other_123_00112233445566778899aabbccddeeff",
	}
	for _, invalidName := range invalidNames {
		_, ok := parseTestPgDbName(invalidName)
		if ok {
			t.Errorf("accepted invalid test database name %q", invalidName)
		}
	}
}

func TestPgResourcesRedirectMaintenancePoolAndRestore(t *testing.T) {
	popBasePg := Vault.PushSimpleResource(DefaultPgVaultResourceName, []byte(`
authority: "app.example:5432"
user: "app"
password: "app-secret"
db: "app-db"
`))
	defer popBasePg()
	popBaseMaintenance := Vault.PushSimpleResource(MaintenancePgVaultResourceName, []byte(`
authority: "direct.example:5432"
user: "maintenance"
password: "maintenance-secret"
db: "maintenance-db"
`))
	defer popBaseMaintenance()

	app := Vault.RequireSimpleResource(DefaultPgVaultResourceName).Parse()
	maintenance := Vault.RequireSimpleResource(MaintenancePgVaultResourceName).Parse()
	popTest := pushTestPgResources(app, maintenance, "test_exact")

	testApp := Vault.RequireSimpleResource(DefaultPgVaultResourceName)
	testMaintenance := Vault.RequireSimpleResource(MaintenancePgVaultResourceName)
	if got := testApp.RequireString("db"); got != "test_exact" {
		t.Fatalf("test application database = %q, want test_exact", got)
	}
	if got := testMaintenance.RequireString("db"); got != "test_exact" {
		t.Fatalf("test maintenance database = %q, want test_exact", got)
	}
	if got := testMaintenance.RequireString("authority"); got != "direct.example:5432" {
		t.Fatalf("test maintenance authority = %q, want direct authority", got)
	}
	if got := testMaintenance.RequireString("user"); got != "maintenance" {
		t.Fatalf("test maintenance user = %q, want maintenance credentials", got)
	}

	popTest()
	if got := Vault.RequireSimpleResource(DefaultPgVaultResourceName).RequireString("db"); got != "app-db" {
		t.Fatalf("restored application database = %q, want app-db", got)
	}
	if got := Vault.RequireSimpleResource(MaintenancePgVaultResourceName).RequireString("db"); got != "maintenance-db" {
		t.Fatalf("restored maintenance database = %q, want maintenance-db", got)
	}
}

// Installs complete in-memory resources so preflight behavior can be tested
// without reading a developer's vault or opening network connections.
func pushTestEnvironmentPreflightResources(t *testing.T) {
	t.Helper()
	t.Setenv("WARP_ENV", "local")
	t.Setenv("WARP_VAULT_HOME", filepath.Join(t.TempDir(), "vault"))
	t.Setenv("WARP_CONFIG_HOME", filepath.Join(t.TempDir(), "config"))
	t.Setenv("TEST_POSTGRES_HOST", "postgres.test")
	t.Setenv("TEST_REDIS_HOST", "redis.test")
	t.Setenv("BRINGYOUR_POSTGRES_HOSTNAME", "postgres.test")
	t.Setenv("BRINGYOUR_REDIS_HOSTNAME", "redis.test")
	popPg := Vault.PushSimpleResource(DefaultPgVaultResourceName, []byte(`
authority: "{{ env:TEST_POSTGRES_HOST }}:5432"
user: "test"
password: "not-a-secret"
db: "test"
`))
	popRedis := Vault.PushSimpleResource("redis.yml", []byte(`
authority: "{{ env:TEST_REDIS_HOST }}:6379"
password: ""
db: 0
cluster: false
`))
	popDbConfig := Config.PushSimpleResource(DefaultPgConfigResourceName, []byte(`
min_connections: 1
max_connections: 2
`))
	popRedisConfig := Config.PushSimpleResource("redis.yml", []byte(`
min_connections: 1
max_connections: 2
`))
	t.Cleanup(func() {
		popRedisConfig()
		popDbConfig()
		popRedis()
		popPg()
	})
}

// An unset or non-local environment is a deterministic configuration error,
// never a flaky test attempt.
func TestTestEnvironmentNameRequiresLocal(t *testing.T) {
	cases := []struct {
		env      string
		expected string
	}{
		{env: "", expected: "WARP_ENV must be set to local"},
		{env: "main", expected: `WARP_ENV must be local, got "main"`},
	}
	for _, c := range cases {
		t.Setenv("WARP_ENV", c.env)
		err := validateTestEnvironmentName()
		if err == nil || !strings.Contains(err.Error(), c.expected) {
			t.Errorf("WARP_ENV=%q error = %v; want %q", c.env, err, c.expected)
		}
	}
}

// Every PostgreSQL/Redis vault and pool resource consumed during setup must be
// named before any service probe or retry can begin.
func TestTestEnvironmentPreflightReportsEachMissingResource(t *testing.T) {
	t.Setenv("WARP_ENV", "local")
	t.Setenv("WARP_VAULT_HOME", filepath.Join(t.TempDir(), "vault"))
	t.Setenv("WARP_CONFIG_HOME", filepath.Join(t.TempDir(), "config"))
	fixtures := []struct {
		resolver *Resolver
		name     string
		content  []byte
		expected string
	}{
		{
			resolver: Vault,
			name:     DefaultPgVaultResourceName,
			content:  []byte("authority: postgres.test:5432\nuser: test\npassword: test\ndb: test\n"),
			expected: "required vault resource pg.yml",
		},
		{
			resolver: Vault,
			name:     "redis.yml",
			content:  []byte("authority: redis.test:6379\npassword: \"\"\ndb: 0\ncluster: false\n"),
			expected: "required vault resource redis.yml",
		},
		{
			resolver: Config,
			name:     DefaultPgConfigResourceName,
			content:  []byte("min_connections: 1\nmax_connections: 2\n"),
			expected: "required config resource db.yml",
		},
		{
			resolver: Config,
			name:     "redis.yml",
			content:  []byte("min_connections: 1\nmax_connections: 2\n"),
			expected: "required config resource redis.yml",
		},
	}
	for missingIndex, missingFixture := range fixtures {
		pops := []func(){}
		for fixtureIndex, fixture := range fixtures {
			if fixtureIndex != missingIndex {
				pops = append(pops, fixture.resolver.PushSimpleResource(fixture.name, fixture.content))
			}
		}
		probeCalled := false
		err := preflightTestEnvironment(func(context.Context, string, testEnvironmentConfiguration) error {
			probeCalled = true
			return nil
		})
		for i := len(pops) - 1; 0 <= i; i -= 1 {
			pops[i]()
		}
		if err == nil || !strings.Contains(err.Error(), missingFixture.expected) {
			t.Errorf("missing %s error = %v; want %q", missingFixture.name, err, missingFixture.expected)
		}
		if probeCalled {
			t.Errorf("missing %s reached the service probe", missingFixture.name)
		}
	}
}

// A valid portable fixture expands environment-backed hostnames and probes
// both services in deterministic order.
func TestTestEnvironmentPreflightExpandsAndProbesPortableResources(t *testing.T) {
	pushTestEnvironmentPreflightResources(t)
	authorities := []string{}
	err := preflightTestEnvironment(func(
		ctx context.Context,
		serviceName string,
		configuration testEnvironmentConfiguration,
	) error {
		if _, ok := ctx.Deadline(); !ok {
			t.Error("service probe context has no deadline")
		}
		authorities = append(authorities, testEnvironmentServiceAuthority(serviceName, configuration))
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	connect.AssertEqual(t, authorities, []string{"postgres.test:5432", "redis.test:6379"})
}

// A missing environment value referenced by a fixture fails during resource
// validation rather than entering network setup or the flaky retry loop.
func TestTestEnvironmentPreflightReportsMissingFixtureEnvironment(t *testing.T) {
	pushTestEnvironmentPreflightResources(t)
	t.Setenv("TEST_POSTGRES_HOST", "")
	probeCalled := false
	err := preflightTestEnvironment(func(context.Context, string, testEnvironmentConfiguration) error {
		probeCalled = true
		return nil
	})
	if err == nil || !strings.Contains(err.Error(), "Missing env var TEST_POSTGRES_HOST") {
		t.Fatalf("preflight error = %v; want missing fixture environment", err)
	}
	if probeCalled {
		t.Fatal("invalid fixture reached the service probe")
	}
}

// An unavailable dependency is reported on its first bounded probe; Redis's
// two-minute transient operation retry is reserved for an environment that was
// reachable when the test started.
func TestTestEnvironmentPreflightReportsUnavailableService(t *testing.T) {
	pushTestEnvironmentPreflightResources(t)
	redisUnavailableErr := errors.New("redis test endpoint refused the connection")
	authorities := []string{}
	err := preflightTestEnvironment(func(
		ctx context.Context,
		serviceName string,
		configuration testEnvironmentConfiguration,
	) error {
		authority := testEnvironmentServiceAuthority(serviceName, configuration)
		authorities = append(authorities, authority)
		if authority == "redis.test:6379" {
			return redisUnavailableErr
		}
		return nil
	})
	if !errors.Is(err, redisUnavailableErr) {
		t.Fatalf("preflight error = %v; want Redis probe error", err)
	}
	connect.AssertEqual(t, authorities, []string{"postgres.test:5432", "redis.test:6379"})
}

// Redis-only integration tests diagnose their exact missing fixture without
// depending on the PostgreSQL or pool configuration resources.
func TestLoadTestRedisLeaseConfigurationReportsMissingFixture(t *testing.T) {
	t.Setenv("WARP_ENV", "local")
	t.Setenv("WARP_VAULT_HOME", filepath.Join(t.TempDir(), "vault"))
	_, err := loadTestRedisLeaseConfiguration()
	if err == nil || !strings.Contains(err.Error(), "required vault resource redis.yml") {
		t.Fatalf("Redis fixture error = %v; want missing redis.yml", err)
	}
}

// TestRunRetriesUntilPass checks every failure mode is retried: attempt 1
// panics, 2 calls t.Fail, 3 fails an assertion (assert.Equal -> FailNow ->
// runtime.Goexit), and 4 passes. Each failure is recorded only on the retryTB
// wrapper, so the real *testing.T never fails and the test passes.
func TestRunRetriesUntilPass(t *testing.T) {
	var attempts atomic.Int32
	var preflights atomic.Int32
	testEnv := retryTestEnv(3)
	testEnv.runWithSetup(t, func(tb testing.TB) {
		switch attempts.Add(1) {
		case 1:
			panic("flaky panic on the first attempt")
		case 2:
			tb.Fail()
		case 3:
			connect.AssertEqual(tb, 1, 2)
		}
		// the fourth attempt falls through and passes
	}, func() error {
		preflights.Add(1)
		return nil
	}, func() func() {
		return func() {}
	})
	if got := attempts.Load(); got != 4 {
		t.Fatalf("expected 4 attempts before success, got %d", got)
	}
	if got := preflights.Load(); got != 1 {
		t.Fatalf("preflight count = %d; want 1 outside the retry loop", got)
	}
}

// TestRunFailsAfterExhaustion checks retry does not swallow real failures: a
// failure that persists across every attempt must still fail the test. Run
// calls t.FailNow once reruns are exhausted, so we run that case in a subprocess
// and require it to exit non-zero.
func TestRunFailsAfterExhaustion(t *testing.T) {
	if os.Getenv("URNETWORK_RERUN_EXHAUSTION_CHILD") == "1" {
		// Child process: always fails, so Run exhausts its reruns and fails.
		runRetryTestEnv(t, retryTestEnv(1), func(tb testing.TB) {
			tb.Fatal("persistent failure")
		})
		return
	}

	cmd := exec.Command(os.Args[0], "-test.run=^TestRunFailsAfterExhaustion$", "-test.v")
	cmd.Env = append(os.Environ(), "URNETWORK_RERUN_EXHAUSTION_CHILD=1")
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected the child test to fail after exhausting reruns, but it passed:\n%s", out)
	}
	t.Logf("child test failed after exhausting reruns, as expected:\n%s", out)
}

// TestRunReportsPanicOriginAfterExhaustion checks that retry recovery retains
// the callback stack. Without it, the final re-panic points only at TestEnv.Run
// and hides the line that actually failed.
func TestRunReportsPanicOriginAfterExhaustion(t *testing.T) {
	if os.Getenv("URNETWORK_RERUN_PANIC_CHILD") == "1" {
		runRetryTestEnv(t, retryTestEnv(0), func(tb testing.TB) {
			panic("persistent panic")
		})
		return
	}

	cmd := exec.Command(os.Args[0], "-test.run=^TestRunReportsPanicOriginAfterExhaustion$", "-test.v")
	cmd.Env = append(os.Environ(), "URNETWORK_RERUN_PANIC_CHILD=1")
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected the child test to fail after the panic, but it passed:\n%s", out)
	}
	output := string(out)
	if !strings.Contains(output, "persistent panic") {
		t.Fatalf("expected panic value in child output:\n%s", out)
	}
	if !strings.Contains(output, "TestRunReportsPanicOriginAfterExhaustion.func1") {
		t.Fatalf("expected callback origin in child output:\n%s", out)
	}
}

func TestRedisDbCandidatesExcludeCoordinatorAndReservedDatabases(t *testing.T) {
	candidates := testRedisDbCandidates(6, 3, 0)
	expected := []int{1, 2, 4, 5}
	connect.AssertEqual(t, candidates, expected)
}

func TestRedisDbCandidatesWrapTheirStartingOffset(t *testing.T) {
	candidates := testRedisDbCandidates(6, 3, 3)
	expected := []int{4, 5, 1, 2}
	connect.AssertEqual(t, candidates, expected)
}

func TestRedisDbCandidatesHandleNegativeOffsets(t *testing.T) {
	candidates := testRedisDbCandidates(5, 2, -1)
	expected := []int{4, 1, 3}
	connect.AssertEqual(t, candidates, expected)
}

// An exhausted client-level dial sequence is still one transient setup error;
// the bounded lease setup horizon must give it another operation attempt.
func TestRedisLeaseConnectionOperationRetriesTransientFailure(t *testing.T) {
	attemptCount := 0
	err := retryTestRedisLeaseConnectionOperation(context.Background(), func(ctx context.Context) error {
		attemptCount += 1
		if _, ok := ctx.Deadline(); !ok {
			t.Fatal("lease retry operation context has no deadline")
		}
		if attemptCount == 1 {
			return &net.DNSError{
				Err:       "i/o timeout",
				Name:      "local-redis.bringyour.com",
				IsTimeout: true,
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if attemptCount != 2 {
		t.Fatalf("operation attempts = %d; want 2", attemptCount)
	}
}

// Authentication, protocol, and configuration errors are not made flaky by
// retrying them as if they were transport failures.
func TestRedisLeaseConnectionOperationRejectsPermanentFailure(t *testing.T) {
	permanentErr := errors.New("redis lease configuration rejected")
	attemptCount := 0
	err := retryTestRedisLeaseConnectionOperation(context.Background(), func(context.Context) error {
		attemptCount += 1
		return permanentErr
	})
	if !errors.Is(err, permanentErr) {
		t.Fatalf("operation error = %v; want %v", err, permanentErr)
	}
	if attemptCount != 1 {
		t.Fatalf("operation attempts = %d; want 1", attemptCount)
	}
}

// Caller cancellation remains stronger than the setup retry budget.
func TestRedisLeaseConnectionOperationStopsAfterCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	attemptCount := 0
	err := retryTestRedisLeaseConnectionOperation(ctx, func(context.Context) error {
		attemptCount += 1
		return &net.DNSError{
			Err:       "i/o timeout",
			Name:      "local-redis.bringyour.com",
			IsTimeout: true,
		}
	})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("operation error = %v; want context cancellation", err)
	}
	if attemptCount != 0 {
		t.Fatalf("operation attempts = %d; want 0", attemptCount)
	}
}

func TestRedisDatabaseLeaseRenewsWhileOwnerIsActive(t *testing.T) {
	authority, password, reservedDb := testRedisLeaseConfig(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	token := strconv.Itoa(os.Getpid()) + "-" + strconv.FormatInt(time.Now().UnixNano(), 10)
	lease := acquireTestRedisDbLease(
		ctx,
		authority,
		password,
		reservedDb,
		token,
		0,
		180*time.Millisecond,
	)
	defer lease.release(context.Background())

	time.Sleep(550 * time.Millisecond)
	value, err := lease.client.Get(ctx, lease.key).Result()
	if err != nil {
		t.Fatalf("read renewed lease: %v", err)
	}
	if value != token {
		t.Fatalf("renewed lease owner = %q; want %q", value, token)
	}
	ttl, err := lease.client.PTTL(ctx, lease.key).Result()
	if err != nil {
		t.Fatalf("read renewed lease ttl: %v", err)
	}
	if ttl <= 0 {
		t.Fatalf("renewed lease ttl = %s; want positive", ttl)
	}
}

// Reads and probes only the Redis dependency needed by lease integration
// tests, without imposing an unrelated PostgreSQL requirement.
func testRedisLeaseConfig(t *testing.T) (authority string, password string, reservedDb int) {
	t.Helper()
	configuration, err := loadTestRedisLeaseConfiguration()
	if err == nil {
		err = preflightTestEnvironmentService(
			"redis",
			configuration,
			probeTestEnvironmentService,
		)
	}
	if err != nil {
		t.Fatalf("redis integration test preflight: %v", err)
	}
	return configuration.redisAuthority,
		configuration.redisPassword,
		configuration.redisReservedDb
}

func testRedisLeaseToken() string {
	return strconv.Itoa(os.Getpid()) + "-" + strconv.FormatInt(time.Now().UnixNano(), 10)
}

// TestRedisDatabaseLeaseReleaseSurvivesRetriedRelease simulates the release
// script executing server-side while its response is lost on a broken
// connection: go-redis then retries the script, and the retry must read the
// released marker as success instead of misreporting the lease as not owned.
func TestRedisDatabaseLeaseReleaseSurvivesRetriedRelease(t *testing.T) {
	authority, password, reservedDb := testRedisLeaseConfig(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	lease := acquireTestRedisDbLease(
		ctx,
		authority,
		password,
		reservedDb,
		testRedisLeaseToken(),
		0,
		time.Minute,
	)

	first, err := lease.client.Eval(
		ctx,
		testRedisLeaseReleaseScript,
		[]string{lease.key, lease.releasedKey},
		lease.token,
		testRedisLeaseReleasedMarkerTtl.Milliseconds(),
	).Int64()
	if err != nil {
		t.Fatalf("first release attempt: %v", err)
	}
	if first != 1 {
		t.Fatalf("first release attempt = %d; want 1", first)
	}

	// the retried release must not panic
	lease.release(context.Background())
}

// TestRedisDatabaseLeaseAcquireClaimsOwnTokenAfterLostSetResponse simulates a
// SET NX that the server applied while the client's response was lost: the
// retried SET NX reports not-acquired even though the key holds this process's
// token, and acquisition must claim the lease instead of skipping the db.
func TestRedisDatabaseLeaseAcquireClaimsOwnTokenAfterLostSetResponse(t *testing.T) {
	authority, password, reservedDb := testRedisLeaseConfig(t)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	token := testRedisLeaseToken()

	client := redis.NewClient(&redis.Options{
		Addr:     authority,
		Password: password,
		DB:       testRedisLeaseCoordinatorDb,
	})
	defer client.Close()

	config, err := client.ConfigGet(ctx, "databases").Result()
	if err != nil {
		t.Fatal(err)
	}
	databaseCount, err := strconv.Atoi(config["databases"])
	if err != nil {
		t.Fatal(err)
	}

	// write the lost-response state into the first free candidate db
	preOwnedDb := -1
	for _, db := range testRedisDbCandidates(databaseCount, reservedDb, 0) {
		key := fmt.Sprintf("urnetwork:server-test:redis-db-lease:%d", db)
		acquired, err := client.SetNX(ctx, key, token, time.Minute).Result()
		if err != nil {
			t.Fatal(err)
		}
		if acquired {
			preOwnedDb = db
			break
		}
	}
	if preOwnedDb < 0 {
		t.Fatal("no free redis test db to stage the lost-response state")
	}

	// an offset of preOwnedDb-1 makes preOwnedDb the first candidate scanned
	lease := acquireTestRedisDbLease(
		ctx,
		authority,
		password,
		reservedDb,
		token,
		preOwnedDb-1,
		time.Minute,
	)
	defer lease.release(context.Background())

	if lease.db != preOwnedDb {
		t.Fatalf("acquire leased db %d; want it to claim its own token on db %d", lease.db, preOwnedDb)
	}
}

// TestRedisDatabaseLeaseReleaseDetectsForeignOwner: a lease key rewritten by
// another owner must fail release with the foreign-owner diagnostic.
func TestRedisDatabaseLeaseReleaseDetectsForeignOwner(t *testing.T) {
	authority, password, reservedDb := testRedisLeaseConfig(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	lease := acquireTestRedisDbLease(
		ctx,
		authority,
		password,
		reservedDb,
		testRedisLeaseToken(),
		0,
		time.Minute,
	)

	err := lease.client.Set(ctx, lease.key, "foreign-token", time.Minute).Err()
	if err != nil {
		t.Fatal(err)
	}

	defer func() {
		r := recover()
		// release closes lease.client before panicking; clean the stomped
		// key with a fresh client so the db frees up for concurrent runs
		cleanup := redis.NewClient(&redis.Options{
			Addr:     authority,
			Password: password,
			DB:       testRedisLeaseCoordinatorDb,
		})
		cleanup.Del(context.Background(), lease.key)
		cleanup.Close()
		if r == nil {
			t.Fatal("expected release to panic for a foreign-owned lease")
		}
		if !strings.Contains(fmt.Sprint(r), "owned by another process") {
			t.Fatalf("expected foreign-owner diagnostic, got: %v", r)
		}
	}()
	lease.release(context.Background())
}

// TestRedisDatabaseLeaseReleaseDetectsMissingKey: a lease key that vanished
// entirely (flush, expiry) must still fail release with the not-owned
// diagnostic.
func TestRedisDatabaseLeaseReleaseDetectsMissingKey(t *testing.T) {
	authority, password, reservedDb := testRedisLeaseConfig(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	lease := acquireTestRedisDbLease(
		ctx,
		authority,
		password,
		reservedDb,
		testRedisLeaseToken(),
		0,
		time.Minute,
	)

	if err := lease.client.Del(ctx, lease.key).Err(); err != nil {
		t.Fatal(err)
	}

	defer func() {
		r := recover()
		if r == nil {
			t.Fatal("expected release to panic for a missing lease key")
		}
		if !strings.Contains(fmt.Sprint(r), "was not owned during release") {
			t.Fatalf("expected not-owned diagnostic, got: %v", r)
		}
	}()
	lease.release(context.Background())
}

func TestRedisDatabaseLeaseSeparatesProcesses(t *testing.T) {
	const (
		roleEnv = "URNETWORK_REDIS_LEASE_TEST_ROLE"
		dirEnv  = "URNETWORK_REDIS_LEASE_TEST_DIR"
	)

	if role := os.Getenv(roleEnv); role != "" {
		if err := preflightTestEnvironment(probeTestEnvironmentService); err != nil {
			t.Fatalf("local integration test preflight: %v", err)
		}
		teardown := (&TestEnv{ApplyDbMigrations: false}).setup()
		defer teardown()

		dir := os.Getenv(dirEnv)
		path := filepath.Join(dir, role)
		err := os.WriteFile(path, []byte(strconv.Itoa(RedisDb())), 0o600)
		if err != nil {
			t.Fatal(err)
		}

		// The peer has to finish a whole TestEnv setup (redis lease + pg
		// database creation) before it can write its marker, and that cost is
		// not bounded by anything this test controls: it is ~1.2s idle but was
		// observed at ~30s during a loaded -race suite against a pg carrying
		// abandoned test databases. This budget only has to be longer than a
		// pathological setup — the parent still bounds the test overall — so
		// keep it generous. A tight budget here fails the run for being slow,
		// which says nothing about lease separation.
		started := time.Now()
		deadline := started.Add(90 * time.Second)
		for {
			first, firstErr := os.ReadFile(filepath.Join(dir, "first"))
			second, secondErr := os.ReadFile(filepath.Join(dir, "second"))
			if firstErr == nil && secondErr == nil {
				if string(first) == string(second) {
					t.Fatalf("parallel processes leased the same redis db %s", first)
				}
				return
			}
			if deadline.Before(time.Now()) {
				t.Fatalf(
					"timed out after %s waiting for both lease markers: first=%v second=%v",
					time.Since(started),
					firstErr,
					secondErr,
				)
			}
			time.Sleep(10 * time.Millisecond)
		}
	}

	dir := t.TempDir()
	newChild := func(role string) *exec.Cmd {
		cmd := exec.Command(
			os.Args[0],
			"-test.run=^TestRedisDatabaseLeaseSeparatesProcesses$",
			"-test.v",
		)
		cmd.Env = append(
			os.Environ(),
			roleEnv+"="+role,
			dirEnv+"="+dir,
		)
		return cmd
	}

	first := newChild("first")
	second := newChild("second")
	var firstOutput strings.Builder
	var secondOutput strings.Builder
	first.Stdout = &firstOutput
	first.Stderr = &firstOutput
	second.Stdout = &secondOutput
	second.Stderr = &secondOutput

	if err := first.Start(); err != nil {
		t.Fatal(err)
	}
	if err := second.Start(); err != nil {
		t.Fatal(err)
	}
	firstErr := first.Wait()
	secondErr := second.Wait()
	if firstErr != nil {
		t.Fatalf("first lease child failed: %v\n%s", firstErr, firstOutput.String())
	}
	if secondErr != nil {
		t.Fatalf("second lease child failed: %v\n%s", secondErr, secondOutput.String())
	}
}

// ---- test listen port allocator ------------------------------------------
//
// Deterministic pins for the two allocator rules from certification failure
// c12-1 (see the allocator doc in test_util.go). The scope test asserts the
// address passed to the OS and then occupies that exact address, avoiding
// platform-specific rules for overlapping wildcard and specific binds.

// TestReserveTestListenPortsStayBelowEphemeralRange: every allocated port
// must sit below the OS ephemeral range (macOS: 49152+, Linux default:
// 32768+). A port from the ephemeral range can be handed to any outbound
// dial in the release->bind window — that is the collision that killed
// c12-1 — so allocation from that range is a regression regardless of how
// rarely it collides.
func TestReserveTestListenPortsStayBelowEphemeralRange(t *testing.T) {
	ports, release, err := ReserveTestListenPorts(
		"tcp", "tcp", "tcp", "tcp", "udp", "udp",
	)
	if err != nil {
		t.Fatalf("reserve: %v", err)
	}
	defer release()
	for i, port := range ports {
		if port < testListenPortFloor || testListenPortCeiling <= port {
			t.Fatalf(
				"port[%d] = %d outside [%d, %d): an ephemeral-range port can be lost to the process's own outbound dials between release and server bind",
				i, port, testListenPortFloor, testListenPortCeiling,
			)
		}
	}
}

// The probe must use the wildcard address the servers actually bind and skip
// candidates already occupied at that scope. TCP and UDP have separate bind
// implementations, so both paths are pinned.
func TestReserveTestListenPortsProbeWildcardScope(t *testing.T) {
	for _, network := range []string{"tcp", "udp"} {
		t.Run(network, func(t *testing.T) {
			// Start with a candidate the allocator proved wildcard-free.
			ports, release, err := ReserveTestListenPorts(network)
			if err != nil {
				t.Fatalf("reserve: %v", err)
			}
			occupiedPort := ports[0]
			release()

			expectedAddr := fmt.Sprintf("0.0.0.0:%d", occupiedPort)
			if actualAddr := testListenPortAddress(occupiedPort); actualAddr != expectedAddr {
				t.Fatalf("probe address = %q, want server wildcard %q", actualAddr, expectedAddr)
			}

			var occupier io.Closer
			switch network {
			case "tcp":
				occupier, err = net.Listen("tcp4", expectedAddr)
			case "udp":
				occupier, err = net.ListenPacket("udp4", expectedAddr)
			}
			if err != nil {
				t.Fatalf("occupy wildcard port %d: %v", occupiedPort, err)
			}
			defer occupier.Close()

			// Rewind so the occupied port is the next candidate. The matching
			// wildcard probe must skip it.
			atomic.StoreInt64(&testListenPortNext, int64(occupiedPort))
			if next := testNextListenPortCandidate(); next != occupiedPort {
				t.Fatalf("rewind: next candidate = %d, want %d", next, occupiedPort)
			}
			ports, release, err = ReserveTestListenPorts(network)
			if err != nil {
				t.Fatalf("reserve with occupied candidate: %v", err)
			}
			defer release()
			if ports[0] == occupiedPort {
				t.Fatalf("allocator returned wildcard-occupied port %d", occupiedPort)
			}
		})
	}
}
