// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sample.proto

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// one sample per FindProviders2 call: the loaded candidate pool (after redis
// shard sub-sampling, before any per-call filtering) in scaled-weight
// descending order, and the chosen providers in result order. Together with
// the call args this is enough to replay the selection.
//
// client and network ids are anonymized 16-byte pseudonyms (see
// server/stats). The same real id maps to the same pseudonym across every
// sample, so providers can be traced through the stats without being
// matchable to production ids.
type FindProviders2Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMilli uint64                 `protobuf:"varint,1,opt,name=time_unix_milli,json=timeUnixMilli,proto3" json:"time_unix_milli,omitempty"`
	// caller country code (lowercase), resolved from the caller ip. The
	// caller itself is not identified.
	CallerCountryCode string `protobuf:"bytes,2,opt,name=caller_country_code,json=callerCountryCode,proto3" json:"caller_country_code,omitempty"`
	RankMode          string `protobuf:"bytes,3,opt,name=rank_mode,json=rankMode,proto3" json:"rank_mode,omitempty"`
	ForceMinimum      bool   `protobuf:"varint,4,opt,name=force_minimum,json=forceMinimum,proto3" json:"force_minimum,omitempty"`
	ForceCount        bool   `protobuf:"varint,5,opt,name=force_count,json=forceCount,proto3" json:"force_count,omitempty"`
	// the requested count and the effective count after the min block size
	RequestedCount int32 `protobuf:"varint,6,opt,name=requested_count,json=requestedCount,proto3" json:"requested_count,omitempty"`
	EffectiveCount int32 `protobuf:"varint,7,opt,name=effective_count,json=effectiveCount,proto3" json:"effective_count,omitempty"`
	// shape of the specs, not the specs themselves
	SpecLocationCount       int32 `protobuf:"varint,8,opt,name=spec_location_count,json=specLocationCount,proto3" json:"spec_location_count,omitempty"`
	SpecLocationGroupCount  int32 `protobuf:"varint,9,opt,name=spec_location_group_count,json=specLocationGroupCount,proto3" json:"spec_location_group_count,omitempty"`
	SpecClientCount         int32 `protobuf:"varint,10,opt,name=spec_client_count,json=specClientCount,proto3" json:"spec_client_count,omitempty"`
	SpecBestAvailable       bool  `protobuf:"varint,11,opt,name=spec_best_available,json=specBestAvailable,proto3" json:"spec_best_available,omitempty"`
	ExcludeClientCount      int32 `protobuf:"varint,12,opt,name=exclude_client_count,json=excludeClientCount,proto3" json:"exclude_client_count,omitempty"`
	ExcludeDestinationCount int32 `protobuf:"varint,13,opt,name=exclude_destination_count,json=excludeDestinationCount,proto3" json:"exclude_destination_count,omitempty"`
	// redis sample shard load time for this call
	LoadMillis float32 `protobuf:"fixed32,14,opt,name=load_millis,json=loadMillis,proto3" json:"load_millis,omitempty"`
	// total loaded pool size. when larger than len(candidates) the export
	// was capped and the lowest-weight tail was dropped.
	PoolCount  int32        `protobuf:"varint,15,opt,name=pool_count,json=poolCount,proto3" json:"pool_count,omitempty"`
	Candidates []*Candidate `protobuf:"bytes,16,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// chosen (anonymized) client ids in result order (after tier banding)
	ChosenClientIds [][]byte `protobuf:"bytes,17,rep,name=chosen_client_ids,json=chosenClientIds,proto3" json:"chosen_client_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindProviders2Sample) Reset() {
	*x = FindProviders2Sample{}
	mi := &file_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProviders2Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProviders2Sample) ProtoMessage() {}

func (x *FindProviders2Sample) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProviders2Sample.ProtoReflect.Descriptor instead.
func (*FindProviders2Sample) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{0}
}

func (x *FindProviders2Sample) GetTimeUnixMilli() uint64 {
	if x != nil {
		return x.TimeUnixMilli
	}
	return 0
}

func (x *FindProviders2Sample) GetCallerCountryCode() string {
	if x != nil {
		return x.CallerCountryCode
	}
	return ""
}

func (x *FindProviders2Sample) GetRankMode() string {
	if x != nil {
		return x.RankMode
	}
	return ""
}

func (x *FindProviders2Sample) GetForceMinimum() bool {
	if x != nil {
		return x.ForceMinimum
	}
	return false
}

func (x *FindProviders2Sample) GetForceCount() bool {
	if x != nil {
		return x.ForceCount
	}
	return false
}

func (x *FindProviders2Sample) GetRequestedCount() int32 {
	if x != nil {
		return x.RequestedCount
	}
	return 0
}

func (x *FindProviders2Sample) GetEffectiveCount() int32 {
	if x != nil {
		return x.EffectiveCount
	}
	return 0
}

func (x *FindProviders2Sample) GetSpecLocationCount() int32 {
	if x != nil {
		return x.SpecLocationCount
	}
	return 0
}

func (x *FindProviders2Sample) GetSpecLocationGroupCount() int32 {
	if x != nil {
		return x.SpecLocationGroupCount
	}
	return 0
}

func (x *FindProviders2Sample) GetSpecClientCount() int32 {
	if x != nil {
		return x.SpecClientCount
	}
	return 0
}

func (x *FindProviders2Sample) GetSpecBestAvailable() bool {
	if x != nil {
		return x.SpecBestAvailable
	}
	return false
}

func (x *FindProviders2Sample) GetExcludeClientCount() int32 {
	if x != nil {
		return x.ExcludeClientCount
	}
	return 0
}

func (x *FindProviders2Sample) GetExcludeDestinationCount() int32 {
	if x != nil {
		return x.ExcludeDestinationCount
	}
	return 0
}

func (x *FindProviders2Sample) GetLoadMillis() float32 {
	if x != nil {
		return x.LoadMillis
	}
	return 0
}

func (x *FindProviders2Sample) GetPoolCount() int32 {
	if x != nil {
		return x.PoolCount
	}
	return 0
}

func (x *FindProviders2Sample) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *FindProviders2Sample) GetChosenClientIds() [][]byte {
	if x != nil {
		return x.ChosenClientIds
	}
	return nil
}

// one loaded candidate, with the weights the selection used
type Candidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// anonymized client id
	ClientId []byte `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// anonymized network id
	NetworkId []byte `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// the weight used by the weighted selection for the call's rank mode
	ScaledWeight                 float32 `protobuf:"fixed32,3,opt,name=scaled_weight,json=scaledWeight,proto3" json:"scaled_weight,omitempty"`
	Tier                         int32   `protobuf:"varint,4,opt,name=tier,proto3" json:"tier,omitempty"`
	Score                        int32   `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	ReliabilityWeight            float64 `protobuf:"fixed64,6,opt,name=reliability_weight,json=reliabilityWeight,proto3" json:"reliability_weight,omitempty"`
	IndependentReliabilityWeight float64 `protobuf:"fixed64,7,opt,name=independent_reliability_weight,json=independentReliabilityWeight,proto3" json:"independent_reliability_weight,omitempty"`
	MinRelativeLatencyMillis     int32   `protobuf:"varint,8,opt,name=min_relative_latency_millis,json=minRelativeLatencyMillis,proto3" json:"min_relative_latency_millis,omitempty"`
	MaxBytesPerSecond            int64   `protobuf:"varint,9,opt,name=max_bytes_per_second,json=maxBytesPerSecond,proto3" json:"max_bytes_per_second,omitempty"`
	HasLatencyTest               bool    `protobuf:"varint,10,opt,name=has_latency_test,json=hasLatencyTest,proto3" json:"has_latency_test,omitempty"`
	HasSpeedTest                 bool    `protobuf:"varint,11,opt,name=has_speed_test,json=hasSpeedTest,proto3" json:"has_speed_test,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{1}
}

func (x *Candidate) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *Candidate) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *Candidate) GetScaledWeight() float32 {
	if x != nil {
		return x.ScaledWeight
	}
	return 0
}

func (x *Candidate) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *Candidate) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Candidate) GetReliabilityWeight() float64 {
	if x != nil {
		return x.ReliabilityWeight
	}
	return 0
}

func (x *Candidate) GetIndependentReliabilityWeight() float64 {
	if x != nil {
		return x.IndependentReliabilityWeight
	}
	return 0
}

func (x *Candidate) GetMinRelativeLatencyMillis() int32 {
	if x != nil {
		return x.MinRelativeLatencyMillis
	}
	return 0
}

func (x *Candidate) GetMaxBytesPerSecond() int64 {
	if x != nil {
		return x.MaxBytesPerSecond
	}
	return 0
}

func (x *Candidate) GetHasLatencyTest() bool {
	if x != nil {
		return x.HasLatencyTest
	}
	return false
}

func (x *Candidate) GetHasSpeedTest() bool {
	if x != nil {
		return x.HasSpeedTest
	}
	return false
}

var File_sample_proto protoreflect.FileDescriptor

const file_sample_proto_rawDesc = "" +
	"\n" +
	"\fsample.proto\x12\x06sample\"\xf7\x05\n" +
	"\x14FindProviders2Sample\x12&\n" +
	"\x0ftime_unix_milli\x18\x01 \x01(\x04R\rtimeUnixMilli\x12.\n" +
	"\x13caller_country_code\x18\x02 \x01(\tR\x11callerCountryCode\x12\x1b\n" +
	"\trank_mode\x18\x03 \x01(\tR\brankMode\x12#\n" +
	"\rforce_minimum\x18\x04 \x01(\bR\fforceMinimum\x12\x1f\n" +
	"\vforce_count\x18\x05 \x01(\bR\n" +
	"forceCount\x12'\n" +
	"\x0frequested_count\x18\x06 \x01(\x05R\x0erequestedCount\x12'\n" +
	"\x0feffective_count\x18\a \x01(\x05R\x0eeffectiveCount\x12.\n" +
	"\x13spec_location_count\x18\b \x01(\x05R\x11specLocationCount\x129\n" +
	"\x19spec_location_group_count\x18\t \x01(\x05R\x16specLocationGroupCount\x12*\n" +
	"\x11spec_client_count\x18\n" +
	" \x01(\x05R\x0fspecClientCount\x12.\n" +
	"\x13spec_best_available\x18\v \x01(\bR\x11specBestAvailable\x120\n" +
	"\x14exclude_client_count\x18\f \x01(\x05R\x12excludeClientCount\x12:\n" +
	"\x19exclude_destination_count\x18\r \x01(\x05R\x17excludeDestinationCount\x12\x1f\n" +
	"\vload_millis\x18\x0e \x01(\x02R\n" +
	"loadMillis\x12\x1d\n" +
	"\n" +
	"pool_count\x18\x0f \x01(\x05R\tpoolCount\x121\n" +
	"\n" +
	"candidates\x18\x10 \x03(\v2\x11.sample.CandidateR\n" +
	"candidates\x12*\n" +
	"\x11chosen_client_ids\x18\x11 \x03(\fR\x0fchosenClientIds\"\xcb\x03\n" +
	"\tCandidate\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\fR\tnetworkId\x12#\n" +
	"\rscaled_weight\x18\x03 \x01(\x02R\fscaledWeight\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\x05R\x04tier\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12-\n" +
	"\x12reliability_weight\x18\x06 \x01(\x01R\x11reliabilityWeight\x12D\n" +
	"\x1eindependent_reliability_weight\x18\a \x01(\x01R\x1cindependentReliabilityWeight\x12=\n" +
	"\x1bmin_relative_latency_millis\x18\b \x01(\x05R\x18minRelativeLatencyMillis\x12/\n" +
	"\x14max_bytes_per_second\x18\t \x01(\x03R\x11maxBytesPerSecond\x12(\n" +
	"\x10has_latency_test\x18\n" +
	" \x01(\bR\x0ehasLatencyTest\x12$\n" +
	"\x0ehas_speed_test\x18\v \x01(\bR\fhasSpeedTestB*Z(github.com/urnetwork/server/stats/sampleb\x06proto3"

var (
	file_sample_proto_rawDescOnce sync.Once
	file_sample_proto_rawDescData []byte
)

func file_sample_proto_rawDescGZIP() []byte {
	file_sample_proto_rawDescOnce.Do(func() {
		file_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)))
	})
	return file_sample_proto_rawDescData
}

var file_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sample_proto_goTypes = []any{
	(*FindProviders2Sample)(nil), // 0: sample.FindProviders2Sample
	(*Candidate)(nil),            // 1: sample.Candidate
}
var file_sample_proto_depIdxs = []int32{
	1, // 0: sample.FindProviders2Sample.candidates:type_name -> sample.Candidate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sample_proto_init() }
func file_sample_proto_init() {
	if File_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sample_proto_goTypes,
		DependencyIndexes: file_sample_proto_depIdxs,
		MessageInfos:      file_sample_proto_msgTypes,
	}.Build()
	File_sample_proto = out.File
	file_sample_proto_goTypes = nil
	file_sample_proto_depIdxs = nil
}
