// Code generated by connectgen. DO NOT EDIT.

package connect

import (
	"fmt"
	"testing"

	"github.com/urnetwork/connect"
	"github.com/urnetwork/server"
)

func TestConnectAuto(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectAuto\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeAuto,
		})
	})
}

func TestConnectAutoWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectAutoWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeAuto,
			enableExtender:        true,
		})
	})
}

func TestConnectAutoEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectAutoEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeAuto,
			enableEncryption:      true,
		})
	})
}

func TestConnectAutoEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectAutoEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeAuto,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectAutoEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectAutoEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeAuto,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectAutoEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectAutoEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeAuto,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectDns(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDns\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3Dns,
		})
	})
}

func TestConnectDnsWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3Dns,
			enableExtender:        true,
		})
	})
}

func TestConnectDnsEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3Dns,
			enableEncryption:      true,
		})
	})
}

func TestConnectDnsEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3Dns,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectDnsEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3Dns,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectDnsEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3Dns,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectDnsPump(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsPump\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3DnsPump,
		})
	})
}

func TestConnectDnsPumpWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsPumpWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3DnsPump,
			enableExtender:        true,
		})
	})
}

func TestConnectDnsPumpEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsPumpEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3DnsPump,
			enableEncryption:      true,
		})
	})
}

func TestConnectDnsPumpEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsPumpEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3DnsPump,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectDnsPumpEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsPumpEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3DnsPump,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectDnsPumpEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectDnsPumpEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3DnsPump,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectH1(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH1\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
		})
	})
}

func TestConnectH1WithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH1WithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableExtender:        true,
		})
	})
}

func TestConnectH1Encrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH1Encrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
		})
	})
}

func TestConnectH1EncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH1EncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectH1EncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH1EncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectH1EncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH1EncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectH3(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH3\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
		})
	})
}

func TestConnectH3WithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH3WithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableExtender:        true,
		})
	})
}

func TestConnectH3Encrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH3Encrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
		})
	})
}

func TestConnectH3EncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH3EncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectH3EncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH3EncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectH3EncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectH3EncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoNack\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
		})
	})
}

func TestConnectNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoNackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableExtender:        true,
		})
	})
}

func TestConnectNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoNackEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
		})
	})
}

func TestConnectNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectNoTransportReform(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReform\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack: true,
		})
	})
}

func TestConnectNoTransportReformWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:     true,
			enableExtender: true,
		})
	})
}

func TestConnectNoTransportReformEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:       true,
			enableEncryption: true,
		})
	})
}

func TestConnectNoTransportReformEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:       true,
			enableEncryption: true,
			enableExtender:   true,
		})
	})
}

func TestConnectNoTransportReformEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:       true,
			enableEncryption: true,
			allowFallback:    true,
		})
	})
}

func TestConnectNoTransportReformEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:       true,
			enableEncryption: true,
			allowFallback:    true,
			enableExtender:   true,
		})
	})
}

func TestConnectNoTransportReformNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformNoNack\n")
		testConnect(t, contractTestNone, &testConnectConfig{})
	})
}

func TestConnectNoTransportReformNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformNoNackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableExtender: true,
		})
	})
}

func TestConnectNoTransportReformNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformNoNackEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableEncryption: true,
		})
	})
}

func TestConnectNoTransportReformNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableEncryption: true,
			enableExtender:   true,
		})
	})
}

func TestConnectNoTransportReformNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableEncryption: true,
			allowFallback:    true,
		})
	})
}

func TestConnectNoTransportReformNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableEncryption: true,
			allowFallback:    true,
			enableExtender:   true,
		})
	})
}

func TestConnectNoTransportReformWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformWithNewInstance\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:        true,
			enableNewInstance: true,
		})
	})
}

func TestConnectNoTransportReformWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformWithNewInstanceWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:        true,
			enableNewInstance: true,
			enableExtender:    true,
		})
	})
}

func TestConnectNoTransportReformWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformWithNewInstanceEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
		})
	})
}

func TestConnectNoTransportReformWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
			enableExtender:    true,
		})
	})
}

func TestConnectNoTransportReformWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
			allowFallback:     true,
		})
	})
}

func TestConnectNoTransportReformWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectNoTransportReformWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
			allowFallback:     true,
			enableExtender:    true,
		})
	})
}

func TestConnectWithAsymmetricContracts(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContracts\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsEncrypted\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithAsymmetricContractsEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsEncryptedWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsEncryptedAllowFallback\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithAsymmetricContractsEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsNoNack\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{})
	})
}

func TestConnectWithAsymmetricContractsNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsNoNackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableExtender: true,
		})
	})
}

func TestConnectWithAsymmetricContractsNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsNoNackEncrypted\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableEncryption: true,
		})
	})
}

func TestConnectWithAsymmetricContractsNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableEncryption: true,
			enableExtender:   true,
		})
	})
}

func TestConnectWithAsymmetricContractsNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableEncryption: true,
			allowFallback:    true,
		})
	})
}

func TestConnectWithAsymmetricContractsNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableEncryption: true,
			allowFallback:    true,
			enableExtender:   true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaos(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaos\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosEncrypted\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosEncryptedWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosEncryptedAllowFallback\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosNoNack\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosNoNackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosNoNackEncrypted\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosWithNewInstance\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosWithNewInstanceWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncrypted\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithForceStream(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithForceStream\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithForceStreamWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithForceStreamWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithForceStreamEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithForceStreamEncrypted\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithForceStreamEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithForceStreamEncryptedWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithForceStreamEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithForceStreamEncryptedAllowFallback\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithForceStreamEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithForceStreamEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithNewInstance\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithNewInstanceWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithNewInstanceEncrypted\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithAsymmetricContractsWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithAsymmetricContractsWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestAsymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosH1(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH1\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
		})
	})
}

func TestConnectWithChaosH1WithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH1WithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosH1Encrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH1Encrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithChaosH1EncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH1EncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosH1EncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH1EncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithChaosH1EncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH1EncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH1,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosH3(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH3\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
		})
	})
}

func TestConnectWithChaosH3WithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH3WithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosH3Encrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH3Encrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithChaosH3EncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH3EncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosH3EncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH3EncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithChaosH3EncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosH3EncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			transportMode:         connect.TransportModeH3,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoNack\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
		})
	})
}

func TestConnectWithChaosNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoNackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoNackEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithChaosNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithChaosNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosNoTransportReform(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReform\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos: true,
			enableNack:  true,
		})
	})
}

func TestConnectWithChaosNoTransportReformWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:    true,
			enableNack:     true,
			enableExtender: true,
		})
	})
}

func TestConnectWithChaosNoTransportReformEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableNack:       true,
			enableEncryption: true,
		})
	})
}

func TestConnectWithChaosNoTransportReformEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableNack:       true,
			enableEncryption: true,
			enableExtender:   true,
		})
	})
}

func TestConnectWithChaosNoTransportReformEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableNack:       true,
			enableEncryption: true,
			allowFallback:    true,
		})
	})
}

func TestConnectWithChaosNoTransportReformEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableNack:       true,
			enableEncryption: true,
			allowFallback:    true,
			enableExtender:   true,
		})
	})
}

func TestConnectWithChaosNoTransportReformNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformNoNack\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos: true,
		})
	})
}

func TestConnectWithChaosNoTransportReformNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformNoNackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:    true,
			enableExtender: true,
		})
	})
}

func TestConnectWithChaosNoTransportReformNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformNoNackEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableEncryption: true,
		})
	})
}

func TestConnectWithChaosNoTransportReformNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableEncryption: true,
			enableExtender:   true,
		})
	})
}

func TestConnectWithChaosNoTransportReformNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableEncryption: true,
			allowFallback:    true,
		})
	})
}

func TestConnectWithChaosNoTransportReformNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:      true,
			enableEncryption: true,
			allowFallback:    true,
			enableExtender:   true,
		})
	})
}

func TestConnectWithChaosNoTransportReformWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformWithNewInstance\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:       true,
			enableNack:        true,
			enableNewInstance: true,
		})
	})
}

func TestConnectWithChaosNoTransportReformWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformWithNewInstanceWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:       true,
			enableNack:        true,
			enableNewInstance: true,
			enableExtender:    true,
		})
	})
}

func TestConnectWithChaosNoTransportReformWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformWithNewInstanceEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:       true,
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
		})
	})
}

func TestConnectWithChaosNoTransportReformWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:       true,
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
			enableExtender:    true,
		})
	})
}

func TestConnectWithChaosNoTransportReformWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:       true,
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
			allowFallback:     true,
		})
	})
}

func TestConnectWithChaosNoTransportReformWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosNoTransportReformWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:       true,
			enableNack:        true,
			enableNewInstance: true,
			enableEncryption:  true,
			allowFallback:     true,
			enableExtender:    true,
		})
	})
}

func TestConnectWithChaosWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosWithNewInstance\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
		})
	})
}

func TestConnectWithChaosWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosWithNewInstanceWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosWithNewInstanceEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithChaosWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithChaosWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithChaosWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithChaosWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithNewInstance\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
		})
	})
}

func TestConnectWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithNewInstanceWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithNewInstanceEncrypted\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestNone, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContracts(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContracts\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
		})
	})
}

func TestConnectWithSymmetricContractsWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsEncrypted\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithSymmetricContractsEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsEncryptedWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsEncryptedAllowFallback\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithSymmetricContractsEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsNoNack\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
		})
	})
}

func TestConnectWithSymmetricContractsNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsNoNackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsNoNackEncrypted\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithSymmetricContractsNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithSymmetricContractsNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaos(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaos\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosEncrypted\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosEncryptedWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosEncryptedAllowFallback\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosNoNack(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosNoNack\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosNoNackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosNoNackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosNoNackEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosNoNackEncrypted\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosNoNackEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosNoNackEncryptedWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosNoNackEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosNoNackEncryptedAllowFallback\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosNoNackEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosNoNackEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosWithNewInstance\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosWithNewInstanceWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncrypted\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithChaosWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableChaos:           true,
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithForceStream(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithForceStream\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
		})
	})
}

func TestConnectWithSymmetricContractsWithForceStreamWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithForceStreamWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithForceStreamEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithForceStreamEncrypted\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithSymmetricContractsWithForceStreamEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithForceStreamEncryptedWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithForceStreamEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithForceStreamEncryptedAllowFallback\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithSymmetricContractsWithForceStreamEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithForceStreamEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			forceStream:           true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithNewInstance(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithNewInstance\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
		})
	})
}

func TestConnectWithSymmetricContractsWithNewInstanceWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithNewInstanceWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithNewInstanceEncrypted(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithNewInstanceEncrypted\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
		})
	})
}

func TestConnectWithSymmetricContractsWithNewInstanceEncryptedWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithNewInstanceEncryptedWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			enableExtender:        true,
		})
	})
}

func TestConnectWithSymmetricContractsWithNewInstanceEncryptedAllowFallback(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithNewInstanceEncryptedAllowFallback\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
		})
	})
}

func TestConnectWithSymmetricContractsWithNewInstanceEncryptedAllowFallbackWithExtender(t *testing.T) {
	server.DefaultTestEnv().Run(t, func(t testing.TB) {
		fmt.Printf("[progress]start TestConnectWithSymmetricContractsWithNewInstanceEncryptedAllowFallbackWithExtender\n")
		testConnect(t, contractTestSymmetric, &testConnectConfig{
			enableTransportReform: true,
			enableNack:            true,
			enableNewInstance:     true,
			enableEncryption:      true,
			allowFallback:         true,
			enableExtender:        true,
		})
	})
}

// 186 cases.
