.git
**/bin
**/build
**/.DS_Store
**/test.out

# binaries
client/build
bringyourctl/bringyourctl
api/api
taskworker/taskworker
gpt/gpt
connect/connect.test
connect/profile/memory
connect/profile/cpu

temp/*

build/androi

.vscode/*
.direnv
android
ICS/
connect/explore