name: Build All Services
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_repos:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the current repository in the 'current-repo' subdirectory
      - name: Checkout Current Repo
        uses: actions/checkout@v3
        with:
          path: bringyour

      # Step 2: Check out another repository in the 'another-repo' subdirectory using GITHUB_TOKEN
      - name: Checkout Another Repo
        uses: actions/checkout@v3
        with:
          repository: bringyour/connect
          path: connect
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        run: |
          docker --version
          echo "Docker is ready to use."
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.27.0"
      - name: Build API image
        run: |
          docker build . -f bringyour/api/Dockerfile.compose

      - name: Build Connect image
        run: |
          docker build . -f bringyour/connect/Dockerfile.compose

      - name: Build Bringyourctl image
        run: |
          docker build . -f bringyour/bringyourctl/Dockerfile.compose

      - name: Build Taskworker image
        run: |
          docker build . -f bringyour/taskworker/Dockerfile.compose
      - name: Build docker-compose containers
        run: |
          cd bringyour && docker-compose build
