name: Measure Troughput
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  measure_throughput:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          echo "Docker is ready to use."

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"

      - name: Precompile Everything
        env:
          REPORT_FILE: report-single.md
          SKIP_METRICS: "true"
        run: |
          go build ./...

      - name: Measure Troughput - single client
        env:
          REPORT_FILE: report-single.md
          SKIP_METRICS: "true"
        run: |
          go run ./measure-throughput

      - name: Measure Troughput - multi client
        env:
          USE_MULTICLIENT: "true"
          REPORT_FILE: report-multi.md
          SKIP_METRICS: "true"
        run: |
          go run ./measure-throughput

      - name: Merge reports
        run: |
          echo "# Bandwidth Measurements" > report.md
          echo "## Single Client" >> report.md
          cat report-single.md >> report.md
          echo "## Multi Client" >> report.md
          cat report-multi.md >> report.md

      - name: Display Report as PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: ./report.md
