// Published versions 794–813 share one ordered artifact/SQL contract. These
// predicates read catalogs only and remain safe before the additive DDL exists.
package monitor

import "strings"

// Keep previously published single predicates byte-for-byte; their owning
// native tests also extract the exact emitted SQL from the complete probe.
func migrationCurrentSuffix(version int, name string, predicates ...string) snMainnetMigrationContract {
	contract := snMainnetMigration(version, name, predicates...)
	if len(predicates) == 1 {
		contract.query = predicates[0]
	}
	return contract
}

func migrationCurrentSuffixArtifacts() []migrationArtifact {
	artifacts := make([]migrationArtifact, 0, len(migrationCurrentSuffixContracts))
	for _, contract := range migrationCurrentSuffixContracts {
		artifacts = append(artifacts, contract.artifact)
	}
	return artifacts
}

func migrationCurrentSuffixArtifactQueries() string {
	queries := make([]string, 0, len(migrationCurrentSuffixContracts))
	for _, contract := range migrationCurrentSuffixContracts {
		queries = append(queries, contract.query)
	}
	return strings.Join(queries, ",\n")
}

var migrationCurrentSuffixContracts = []snMainnetMigrationContract{
	migrationCurrentSuffix(794, "tiered extender directory and release custody",
		snMainnetMigrationColumns("network_extender",
			snMainnetMigrationColumn{name: "directory_tier", kind: "smallint", notNull: true, defaultExpression: "0"},
			snMainnetMigrationColumn{name: "canary_channel", kind: "character varying"}),
		migrationFp2Table("network_extender_release_request"),
		snMainnetMigrationColumns("network_extender_release_request",
			snMainnetMigrationColumn{name: "request_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "identity", kind: "bytea", notNull: true},
			snMainnetMigrationColumn{name: "vantage", kind: "character varying", notNull: true},
			snMainnetMigrationColumn{name: "request_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_extender_release_request", "PRIMARY KEY (request_id)"),
		migrationFp2Index("network_extender_release_request", "network_extender_release_request_identity_request_time", "identity, request_time", "", false),
		migrationFp2Index("network_extender_release_request", "network_extender_release_request_vantage_request_time", "vantage, request_time", "", false),
		migrationFp2Table("network_extender_release"),
		snMainnetMigrationColumns("network_extender_release",
			snMainnetMigrationColumn{name: "release_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "extender_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "identity", kind: "bytea", notNull: true},
			snMainnetMigrationColumn{name: "country_code", kind: "character varying", notNull: true},
			snMainnetMigrationColumn{name: "epoch", kind: "bigint", notNull: true},
			snMainnetMigrationColumn{name: "release_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_extender_release", "PRIMARY KEY (release_id)"),
		migrationFp2Index("network_extender_release", "network_extender_release_extender_id_country_code_release_time", "extender_id, country_code, release_time", "", false),
		migrationFp2Index("network_extender_release", "network_extender_release_release_time", "release_time", "", false),
		migrationFp2Table("network_extender_block_report"),
		snMainnetMigrationColumns("network_extender_block_report",
			snMainnetMigrationColumn{name: "report_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "extender_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "client_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "country_code", kind: "character varying", notNull: true},
			snMainnetMigrationColumn{name: "report_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_extender_block_report", "PRIMARY KEY (report_id)"),
		// PostgreSQL truncates the published 66-byte identifier to 63 bytes.
		migrationFp2Index("network_extender_block_report", "network_extender_block_report_extender_id_country_code_report_t", "extender_id, country_code, report_time", "", false),
		migrationFp2Index("network_extender_block_report", "network_extender_block_report_report_time", "report_time", "", false)),
	migrationCurrentSuffix(795, "extender release identity and epoch index",
		migrationFp2Index("network_extender_release", "network_extender_release_identity_epoch", "identity, epoch, extender_id", "", false)),
	migrationCurrentSuffix(796, "task run-once wake and claim generations", taskRunOnceGenerationArtifactQuery),
	migrationCurrentSuffix(797, "per-network top-level client limit",
		migrationFp2Table("network_top_level_client_limit"),
		snMainnetMigrationColumns("network_top_level_client_limit",
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "top_level_client_limit", kind: "integer", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_top_level_client_limit", "PRIMARY KEY (network_id)")),
	migrationCurrentSuffix(798, "per-client data cap and usage drain custody",
		migrationFp2Table("network_client_data_cap"),
		snMainnetMigrationColumns("network_client_data_cap",
			snMainnetMigrationColumn{name: "client_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "monthly_byte_limit", kind: "bigint"},
			snMainnetMigrationColumn{name: "total_byte_limit", kind: "bigint"},
			snMainnetMigrationColumn{name: "total_period_start", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "total_used_byte_count", kind: "bigint", notNull: true, defaultExpression: "0"},
			snMainnetMigrationColumn{name: "monthly_capped_period_start", kind: "timestamp without time zone"},
			snMainnetMigrationColumn{name: "total_capped", kind: "boolean", notNull: true, defaultExpression: "false"},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_client_data_cap", "PRIMARY KEY (client_id)"),
		migrationFp2Index("network_client_data_cap", "network_client_data_cap_network_id_client_id", "network_id, client_id", "((monthly_byte_limit IS NOT NULL) OR (total_byte_limit IS NOT NULL))", false),
		migrationFp2Index("network_client_data_cap", "network_client_data_cap_total_capped", "client_id", "total_capped", false),
		migrationFp2Index("network_client_data_cap", "network_client_data_cap_monthly_capped", "monthly_capped_period_start", "(monthly_capped_period_start IS NOT NULL)", false),
		migrationFp2Index("network_client_data_cap", "network_client_data_cap_monthly_paused", "client_id", "(monthly_byte_limit = 0)", false),
		migrationFp2Table("network_client_data_usage"),
		snMainnetMigrationColumns("network_client_data_usage",
			snMainnetMigrationColumn{name: "client_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "period_start", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "used_byte_count", kind: "bigint", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_client_data_usage", "PRIMARY KEY (client_id, period_start)"),
		migrationFp2Index("network_client_data_usage", "network_client_data_usage_period_start", "period_start", "", false),
		migrationFp2Table("network_client_data_usage_drain"),
		snMainnetMigrationColumns("network_client_data_usage_drain",
			snMainnetMigrationColumn{name: "block_number", kind: "bigint", notNull: true},
			snMainnetMigrationColumn{name: "shard", kind: "integer", notNull: true},
			snMainnetMigrationColumn{name: "drain_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_client_data_usage_drain", "PRIMARY KEY (block_number, shard)"),
		migrationFp2Index("network_client_data_usage_drain", "network_client_data_usage_drain_drain_time", "drain_time", "", false),
		migrationFp2Table("network_client_data_usage_rollup"),
		snMainnetMigrationColumns("network_client_data_usage_rollup",
			snMainnetMigrationColumn{name: "singleton_id", kind: "smallint", notNull: true},
			snMainnetMigrationColumn{name: "max_drained_block", kind: "bigint", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_client_data_usage_rollup", "PRIMARY KEY (singleton_id)")),
	migrationCurrentSuffix(799, "services contact-sales lead storage",
		migrationFp2Table("services_lead"),
		snMainnetMigrationColumns("services_lead",
			snMainnetMigrationColumn{name: "lead_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "name", kind: "character varying(256)", notNull: true},
			snMainnetMigrationColumn{name: "email", kind: "character varying(256)", notNull: true},
			snMainnetMigrationColumn{name: "company", kind: "character varying(256)", notNull: true},
			snMainnetMigrationColumn{name: "monthly_active_users", kind: "bigint", notNull: true},
			snMainnetMigrationColumn{name: "monthly_data_budget_byte_count", kind: "bigint", notNull: true},
			snMainnetMigrationColumn{name: "message", kind: "text", notNull: true},
			snMainnetMigrationColumn{name: "notify_time", kind: "timestamp without time zone"}),
		snMainnetMigrationConstraints("services_lead", "PRIMARY KEY (lead_id)"),
		migrationFp2Index("services_lead", "services_lead_create_time", "create_time", "", false)),
	migrationCurrentSuffix(800, "per-client ACL group storage",
		migrationFp2Table("network_client_acl_group"),
		snMainnetMigrationColumns("network_client_acl_group",
			snMainnetMigrationColumn{name: "client_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "acl_group", kind: "character varying(32)", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_client_acl_group", "PRIMARY KEY (client_id)"),
		migrationFp2Index("network_client_acl_group", "network_client_acl_group_network_id", "network_id, client_id", "", false)),
	migrationCurrentSuffix(801, "network Embed enablement storage",
		migrationFp2Table("network_embed"),
		snMainnetMigrationColumns("network_embed",
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "enable_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_embed", "PRIMARY KEY (network_id)")),
	migrationCurrentSuffix(802, "network Embed retained disable timestamp",
		snMainnetMigrationColumns("network_embed",
			snMainnetMigrationColumn{name: "disable_time", kind: "timestamp without time zone"})),
	migrationCurrentSuffix(803, "retained contract close source identity and exact owner assignment", contractCloseOwnerArtifactQueries[0]),
	migrationCurrentSuffix(804, "escrow-free source close due index", contractCloseOwnerArtifactQueries[1]),
	migrationCurrentSuffix(805, "unresolved contract close owner registration index", contractCloseOwnerArtifactQueries[2]),
	migrationCurrentSuffix(806, "session associations and durable operation custody",
		snMainnetMigrationColumns("network_client",
			snMainnetMigrationColumn{name: "session_id", kind: "uuid"},
			snMainnetMigrationColumn{name: "session_create_time", kind: "timestamp without time zone"}),
		snMainnetMigrationColumns("auth_code", snMainnetMigrationColumn{name: "origin_session_id", kind: "uuid"}),
		migrationFp2Table("network_session_operation"),
		snMainnetMigrationColumns("network_session_operation",
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "operation_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "action", kind: "character varying(16)", notNull: true},
			snMainnetMigrationColumn{name: "fingerprint", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "actor", kind: "jsonb", notNull: true},
			snMainnetMigrationColumn{name: "credential_epoch", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "target_session_id", kind: "uuid"},
			snMainnetMigrationColumn{name: "kept_session_id", kind: "uuid"},
			snMainnetMigrationColumn{name: "status", kind: "character varying(16)", notNull: true},
			snMainnetMigrationColumn{name: "result", kind: "jsonb"},
			snMainnetMigrationColumn{name: "target_session_ids", kind: "jsonb", notNull: true, defaultExpression: "'[]'::jsonb"},
			snMainnetMigrationColumn{name: "quota_reserved", kind: "boolean", notNull: true, defaultExpression: "true"},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "retain_until", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_session_operation", "PRIMARY KEY (network_id, operation_id)"),
		migrationFp2Index("network_session_operation", "network_session_operation_recovery", "update_time, network_id, operation_id", "((status)::text = ANY ((ARRAY['prepared'::character varying, 'enforced'::character varying])::text[]))", false),
		migrationFp2Index("network_session_operation", "network_session_operation_quota", "network_id, action, create_time", "quota_reserved", false),
		migrationFp2Table("auth_code_redemption"),
		snMainnetMigrationColumns("auth_code_redemption",
			snMainnetMigrationColumn{name: "code_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "request_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "fingerprint", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "credential", kind: "jsonb", notNull: true},
			snMainnetMigrationColumn{name: "status", kind: "character varying(16)", notNull: true},
			snMainnetMigrationColumn{name: "result", kind: "jsonb"},
			snMainnetMigrationColumn{name: "retain_until", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("auth_code_redemption", "PRIMARY KEY (code_sha256, request_id)", "UNIQUE (request_id)"),
		migrationFp2Index("auth_code_redemption", "auth_code_redemption_retention", "retain_until", "", false),
		migrationFp2Table("network_session_index_outbox"),
		snMainnetMigrationColumns("network_session_index_outbox",
			snMainnetMigrationColumn{name: "network_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "revision", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "next_review_time", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("network_session_index_outbox", "PRIMARY KEY (network_id)")),
	migrationCurrentSuffix(807, "active client session lookup index",
		migrationFp2Index("network_client", "network_client_session_active", "network_id, session_id, client_id", "(active AND (session_id IS NOT NULL))", false)),
	migrationCurrentSuffix(808, "active auth-code origin session index",
		migrationFp2Index("auth_code", "auth_code_origin_session", "network_id, origin_session_id", "(active AND (origin_session_id IS NOT NULL))", false)),
	migrationCurrentSuffix(809, "normalized task-function due-order polling index",
		migrationFp2Index("pending_task", "pending_task_function_poll_order",
			"regexp_replace((function_name)::text, '/v[0-9]+'::text, ''::text, 'g'::text), available_block, run_priority DESC, run_max_time_seconds DESC, task_id", "", false)),
	migrationCurrentSuffix(810, "closed-day audit lookup for contracts without an outcome",
		migrationFp2Index("transfer_contract", "transfer_contract_audit_closed_null_day",
			"close_time, contract_id", "((outcome IS NULL) AND (close_time IS NOT NULL))", false)),
	migrationCurrentSuffix(811, "recurring transfer-grant task receipts",
		migrationFp2Table("transfer_balance_grant_run"),
		snMainnetMigrationColumns("transfer_balance_grant_run",
			snMainnetMigrationColumn{name: "run_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "grant_kind", kind: "character varying(32)", notNull: true},
			snMainnetMigrationColumn{name: "start_time", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "end_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("transfer_balance_grant_run", "PRIMARY KEY (run_id, grant_kind)")),
	migrationCurrentSuffix(812, "deadline closure preserves retained usage evidence", contractDeadlineUsageGuardArtifactQuery),
	migrationCurrentSuffix(813, "conservative legacy close checkpoints",
		snMainnetMigrationColumns("contract_close",
			snMainnetMigrationColumn{name: "legacy_checkpoint_byte_count", kind: "bigint"},
			snMainnetMigrationColumn{name: "identified_checkpoint_byte_count", kind: "bigint"})),
}
