// The native-fee artifact follows the actual original-retention migration780.
// A version counter cannot stand in for its signed-input and credited-debit
// storage contract. No custom trigger or function is installed by this schema.
package monitor

// New native-fee tables have only PostgreSQL's checked foreign-key triggers.
// An added user trigger must not silently acquire authority over retained fees.
func snMainnetNativeFeeTriggerCensus(table string) string {
	return "NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('public." + table + "') AND NOT tgisinternal)"
}

// Keep the approved nullable unknown debit in a contradiction hold distinct
// from a credited settlement's mandatory exact debit and original ceiling.
func snMainnetNativeFeeMigrationContract() snMainnetMigrationContract {
	return snMainnetMigration(780, "original native fee settlement and contradiction custody",
		migrationFp2Table("st_operator_native_fee_owner"),
		snMainnetMigrationColumns("st_operator_native_fee_owner",
			snMainnetMigrationColumn{name: "scope_key", kind: "character varying(160)", notNull: true},
			snMainnetMigrationColumn{name: "approver_public_key", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("st_operator_native_fee_owner",
			"PRIMARY KEY (scope_key)",
			"FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_owner", "st_operator_gas_budget", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetMigrationForeignKeyCensus("st_operator_native_fee_owner", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetNativeFeeTriggerCensus("st_operator_native_fee_owner"),
		migrationFp2Table("st_operator_native_fee_policy"),
		snMainnetMigrationColumns("st_operator_native_fee_policy",
			snMainnetMigrationColumn{name: "policy_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "scope_key", kind: "character varying(160)", notNull: true},
			snMainnetMigrationColumn{name: "policy_json", kind: "bytea", notNull: true},
			snMainnetMigrationColumn{name: "authority_json", kind: "bytea", notNull: true},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("st_operator_native_fee_policy",
			"PRIMARY KEY (policy_sha256)",
			"FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_policy", "st_operator_gas_budget", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetMigrationForeignKeyCensus("st_operator_native_fee_policy", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetNativeFeeTriggerCensus("st_operator_native_fee_policy"),
		migrationFp2Table("st_operator_native_fee_settlement"),
		snMainnetMigrationColumns("st_operator_native_fee_settlement",
			snMainnetMigrationColumn{name: "intent_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "attempt", kind: "integer", notNull: true},
			snMainnetMigrationColumn{name: "scope_key", kind: "character varying(160)", notNull: true},
			snMainnetMigrationColumn{name: "logical_key", kind: "character varying(255)", notNull: true},
			snMainnetMigrationColumn{name: "policy_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "transaction_hash", kind: "character varying(66)", notNull: true},
			snMainnetMigrationColumn{name: "statement_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "statement_json", kind: "bytea", notNull: true},
			snMainnetMigrationColumn{name: "debit_rao", kind: "numeric(20,0)", notNull: true},
			snMainnetMigrationColumn{name: "debit_wei", kind: "numeric(78,0)", notNull: true},
			snMainnetMigrationColumn{name: "original_ceiling_wei", kind: "numeric(78,0)", notNull: true},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("st_operator_native_fee_settlement",
			"PRIMARY KEY (intent_id)",
			"CHECK ((debit_rao >= (0)::numeric))",
			"CHECK ((debit_wei >= (0)::numeric))",
			"CHECK ((original_ceiling_wei > (0)::numeric))",
			"FOREIGN KEY (intent_id) REFERENCES st_transaction_intent(intent_id)",
			"FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)",
			"FOREIGN KEY (logical_key) REFERENCES st_operator_gas_intent(logical_key)",
			"FOREIGN KEY (policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)",
			"FOREIGN KEY (intent_id, attempt) REFERENCES st_operator_gas_reservation(intent_id, attempt)",
			"UNIQUE (scope_key, transaction_hash)"),
		financialIndexArtifact("st_operator_native_fee_settlement", "st_operator_native_fee_settlement_scope", "scope_key"),
		financialIndexArtifact("st_operator_native_fee_settlement", "st_operator_native_fee_settlement_logical", "logical_key"),
		snMainnetMigrationForeignKey("st_operator_native_fee_settlement", "st_transaction_intent", "FOREIGN KEY (intent_id) REFERENCES st_transaction_intent(intent_id)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_settlement", "st_operator_gas_budget", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_settlement", "st_operator_gas_intent", "FOREIGN KEY (logical_key) REFERENCES st_operator_gas_intent(logical_key)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_settlement", "st_operator_native_fee_policy", "FOREIGN KEY (policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_settlement", "st_operator_gas_reservation", "FOREIGN KEY (intent_id, attempt) REFERENCES st_operator_gas_reservation(intent_id, attempt)"),
		snMainnetMigrationForeignKeyCensus("st_operator_native_fee_settlement", "FOREIGN KEY (intent_id) REFERENCES st_transaction_intent(intent_id)", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)", "FOREIGN KEY (logical_key) REFERENCES st_operator_gas_intent(logical_key)", "FOREIGN KEY (policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)", "FOREIGN KEY (intent_id, attempt) REFERENCES st_operator_gas_reservation(intent_id, attempt)"),
		snMainnetNativeFeeTriggerCensus("st_operator_native_fee_settlement"),
		migrationFp2Table("st_operator_native_fee_hold"),
		snMainnetMigrationColumns("st_operator_native_fee_hold",
			snMainnetMigrationColumn{name: "intent_id", kind: "uuid", notNull: true},
			snMainnetMigrationColumn{name: "scope_key", kind: "character varying(160)", notNull: true},
			snMainnetMigrationColumn{name: "logical_key", kind: "character varying(255)", notNull: true},
			snMainnetMigrationColumn{name: "first_policy_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "first_statement_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "first_statement_json", kind: "bytea", notNull: true},
			snMainnetMigrationColumn{name: "first_reason", kind: "character varying(255)", notNull: true},
			snMainnetMigrationColumn{name: "maximum_policy_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "maximum_statement_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "maximum_statement_json", kind: "bytea", notNull: true},
			snMainnetMigrationColumn{name: "maximum_debit_wei", kind: "numeric(78,0)"},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true},
			snMainnetMigrationColumn{name: "update_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("st_operator_native_fee_hold",
			"PRIMARY KEY (intent_id)",
			"CHECK ((maximum_debit_wei >= (0)::numeric))",
			"FOREIGN KEY (intent_id) REFERENCES st_transaction_intent(intent_id)",
			"FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)",
			"FOREIGN KEY (logical_key) REFERENCES st_operator_gas_intent(logical_key)",
			"FOREIGN KEY (first_policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)",
			"FOREIGN KEY (maximum_policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)"),
		financialIndexArtifact("st_operator_native_fee_hold", "st_operator_native_fee_hold_scope", "scope_key"),
		snMainnetMigrationForeignKey("st_operator_native_fee_hold", "st_transaction_intent", "FOREIGN KEY (intent_id) REFERENCES st_transaction_intent(intent_id)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_hold", "st_operator_gas_budget", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_hold", "st_operator_gas_intent", "FOREIGN KEY (logical_key) REFERENCES st_operator_gas_intent(logical_key)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_hold", "st_operator_native_fee_policy", "FOREIGN KEY (first_policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_hold", "st_operator_native_fee_policy", "FOREIGN KEY (maximum_policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)"),
		snMainnetMigrationForeignKeyCensus("st_operator_native_fee_hold", "FOREIGN KEY (intent_id) REFERENCES st_transaction_intent(intent_id)", "FOREIGN KEY (scope_key) REFERENCES st_operator_gas_budget(scope_key)", "FOREIGN KEY (logical_key) REFERENCES st_operator_gas_intent(logical_key)", "FOREIGN KEY (first_policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)", "FOREIGN KEY (maximum_policy_sha256) REFERENCES st_operator_native_fee_policy(policy_sha256)"),
		snMainnetNativeFeeTriggerCensus("st_operator_native_fee_hold"),
		migrationFp2Table("st_operator_native_fee_original_object"),
		snMainnetMigrationColumns("st_operator_native_fee_original_object",
			snMainnetMigrationColumn{name: "original_sha256", kind: "character varying(71)", notNull: true},
			snMainnetMigrationColumn{name: "byte_count", kind: "bigint", notNull: true},
			snMainnetMigrationColumn{name: "chunk_count", kind: "integer", notNull: true},
			snMainnetMigrationColumn{name: "create_time", kind: "timestamp without time zone", notNull: true}),
		snMainnetMigrationConstraints("st_operator_native_fee_original_object",
			"PRIMARY KEY (original_sha256)",
			"CHECK ((byte_count > 0))",
			"CHECK ((chunk_count > 0))"),
		snMainnetMigrationForeignKeyCensus("st_operator_native_fee_original_object"),
		snMainnetNativeFeeTriggerCensus("st_operator_native_fee_original_object"),
		migrationFp2Table("st_operator_native_fee_original_chunk"),
		snMainnetMigrationColumns("st_operator_native_fee_original_chunk",
			snMainnetMigrationColumn{name: "original_sha256", kind: "character varying(71)", notNull: true},
			snMainnetMigrationColumn{name: "chunk_index", kind: "integer", notNull: true},
			snMainnetMigrationColumn{name: "original_bytes", kind: "bytea", notNull: true}),
		snMainnetMigrationConstraints("st_operator_native_fee_original_chunk",
			"PRIMARY KEY (original_sha256, chunk_index)",
			"CHECK ((chunk_index >= 0))",
			"CHECK (((octet_length(original_bytes) > 0) AND (octet_length(original_bytes) <= 1048576)))",
			"FOREIGN KEY (original_sha256) REFERENCES st_operator_native_fee_original_object(original_sha256)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_original_chunk", "st_operator_native_fee_original_object", "FOREIGN KEY (original_sha256) REFERENCES st_operator_native_fee_original_object(original_sha256)"),
		snMainnetMigrationForeignKeyCensus("st_operator_native_fee_original_chunk", "FOREIGN KEY (original_sha256) REFERENCES st_operator_native_fee_original_object(original_sha256)"),
		snMainnetNativeFeeTriggerCensus("st_operator_native_fee_original_chunk"),
		migrationFp2Table("st_operator_native_fee_original_reference"),
		snMainnetMigrationColumns("st_operator_native_fee_original_reference",
			snMainnetMigrationColumn{name: "statement_sha256", kind: "character varying(64)", notNull: true},
			snMainnetMigrationColumn{name: "kind", kind: "character varying(32)", notNull: true},
			snMainnetMigrationColumn{name: "original_path", kind: "text", notNull: true},
			snMainnetMigrationColumn{name: "original_sha256", kind: "character varying(71)", notNull: true}),
		snMainnetMigrationConstraints("st_operator_native_fee_original_reference",
			"PRIMARY KEY (statement_sha256, kind)",
			"FOREIGN KEY (original_sha256) REFERENCES st_operator_native_fee_original_object(original_sha256)"),
		snMainnetMigrationForeignKey("st_operator_native_fee_original_reference", "st_operator_native_fee_original_object", "FOREIGN KEY (original_sha256) REFERENCES st_operator_native_fee_original_object(original_sha256)"),
		snMainnetMigrationForeignKeyCensus("st_operator_native_fee_original_reference", "FOREIGN KEY (original_sha256) REFERENCES st_operator_native_fee_original_object(original_sha256)"),
		snMainnetNativeFeeTriggerCensus("st_operator_native_fee_original_reference"))
}
